con2/konsti

- server/src/features/player-assignment/test/utils/verifyUserSignups.ts
- server/src/features/player-assignment/utils/saveUserSignupResults.ts
- server/src/test/setupTests.ts
- server/src/test/test-data-generation/generators/createSignups.ts
* Fix test signup data generation for groups
* Group members don't have signup data, only group leader
* Don't assume first group member is the leader
* Refactor function `getCurrentEnteredGames()`
> Fix test signup data generation for groups

- client/src/views/signup/components/DropRow.tsx
- server/src/features/feedback/feedbackController.ts
- server/src/features/game/gameController.ts
- server/src/features/results/resultsController.ts
- server/src/features/settings/settingsController.ts
- server/src/features/user/userController.ts
- server/src/utils/authHeader.ts
- server/src/utils/jwt.ts
* Simplify auth header check
* Call `res.json` instead of `res.send` since we always respond with json
* Fix regression: rename `provided2` to `provided`
> Simplify auth header check

- client/src/typings/redux.typings.ts
- client/src/utils/loadData.ts
- client/src/views/admin/AdminView.tsx
- client/src/views/admin/adminSlice.ts
- client/src/views/admin/adminThunks.ts
- client/src/views/results/ResultsView.tsx
- shared/constants/apiEndpoints.ts
We have `state.admin.signupTime` and `state.signup.signupTime`. Rename state `admin.signupTime` to avoid confusion.
> Rename state variable admin.signupTime

- client/src/locales/en.json
- client/src/locales/fi.json
- client/src/services/settingsServices.ts
- client/src/typings/redux.typings.ts
- client/src/views/admin/adminSlice.ts
- client/src/views/admin/adminThunks.ts
- client/src/views/admin/adminTypes.ts
- client/src/views/all-games/components/GameDetails.tsx
- server/src/api/apiRoutes.ts
- server/src/features/settings/settingsController.ts
- server/src/features/settings/settingsRepository.ts
- server/src/features/settings/settingsSchema.ts
- server/src/features/settings/settingsService.ts
- shared/constants/apiEndpoints.ts
- shared/typings/api/settings.ts
- shared/typings/models/settings.ts
Allow saving and deleting signup messages from `GameDetails` view. Messages can be used to provide additional information with signup.
> Allow saving signup messages

- client/src/typings/redux.typings.ts
- client/src/views/all-games/allGamesSlice.ts
- client/src/views/results/components/DirectResults.tsx
- client/src/views/results/resultsUtils.ts
- server/src/features/game/gameUtils.ts
- shared/typings/api/games.ts
* Show signup message on results list
* Piti muuttaa Redux storen datamallia niin, että mukaan lisätty myös lisätietoviestit
Ennen:
```
state.allGames.signups: {
usernames: string[]
gameId: string
}
```
Jälkeen:
```
state.allGames.signups: {
users: {
username: string,
signupMessage: string
}[],
gameId: string
}
```
> Show signup message on results list

- client/src/app/Routes.tsx
- client/src/components/LoggedInUserNavigation.tsx
- client/src/views/my-games/MyGamesView.tsx
- shared/config/sharedConfig.ts
- shared/config/sharedConfig.types.ts
* Hide menu links based on shared config
* Add new config `enableGroups`
> Hide menu links based on shared config

- client/src/views/results/components/DirectResults.tsx
Don't show colon after username on overview list. Show it only when signup question answers are toggled.
> Don't show colon after username on overview list

- server/src/config.ts
- server/src/utils/server.ts
Update Express catch-all route to return 404 for api endpoint not found
> Update Express catch-all route to return 404 for api endpoint not found

- client/src/views/all-games/components/GameListTitle.tsx
Start time and participant count are now in one row and
other information has its own row.
> Fix game list title in mobile devices

- client/src/components/ErrorBar.tsx
- client/src/locales/en.json
- client/src/locales/fi.json
- client/src/services/userServices.ts
- client/src/typings/redux.typings.ts
- client/src/utils/store.ts
- client/src/views/admin/adminSlice.ts
- client/src/views/admin/adminThunks.ts
- client/src/views/helper/components/PrivateSignupMessages.tsx
- client/src/views/login/loginSlice.ts
- server/src/api/apiRoutes.ts
- server/src/features/user/signup-message/signupMessageController.test.ts
- server/src/features/user/signup-message/signupMessageController.ts
- server/src/features/user/signup-message/signupMessageService.ts
- shared/constants/apiEndpoints.ts
- shared/typings/models/signupMessage.ts
* Add endpoint to fetch signup messages
* Show private messages in helper UI
* Remove `preloadedState` from store initialization. It messed up reducer specific initial states.
> Add endpoint to fetch signup messages and show in UI

- server/src/test/setupTests.ts
Uuden mongoose-version mukana tuli uusi deprecation-varoitus, että pitää eksplisiittisesti asettaa `strictQuery` arvo. Uusi versio tulee käyttämään `strictQuery: false` eli halutaan käyttää sitä.
> Disable mongoose deprecation messages during tests

- client/package.json
- client/src/locales/en.json
- client/src/locales/fi.json
- client/src/views/admin/AdminView.tsx
- client/src/views/admin/adminService.ts
- client/src/views/admin/adminThunks.ts
- client/webpack.config.babel.ts
- package.json
- server/src/api/apiRoutes.ts
- server/src/config.ts
- server/src/features/sentry-tunnel/sentryTunnelController.ts
- server/src/utils/sentry.ts
- server/src/utils/server.ts
- shared/config/sharedConfig.ts
- shared/constants/apiEndpoints.ts
- yarn.lock
* Lisätään admin-käliin painikkeet Sentryn client- ja bäkkäritestaamiseen. Käytännössä nää vaan aiheuttaa virheen joko frontissa tai bäkkärillä. Bäkkäritesti vaati uuden `/sentry-test` endpointin, mitä vain admin saa kutsua.
* Siirretään `server.ts` Sentryyn liittyvä koodi omaan tiedostoon `sentry.ts`
* Poistetaan Webpack-plugin, mitä käytettiin source mappien uploadaamiseen. Tehdään se jatkossa Github Actionilla.
* Lisätään asetus `enableSentryInDev: false` mikä määrittää, lähetetäänkö Sentry-virheitä dev-ympäristössä. Käytännössä virheitä halutaan lähettää vain Sentrya kehittäessä tai debugatessa. Dev-ympäristön source mappeja ei voi enää buildata, koska Webpack-plugin poistettiin, mutta tää ei ole ongelma, jos lähinnä testataan, että yhteys toimii.
TODO:
* Lisätään seuraavassa PR:ssä …
> Improve Sentry testing and move Sentry stuff to own file

- server/src/middleware/wwwRedirect.ts
* Fix bug with double redirect
* App Runner automatically redirects to https and second redirect will return error
> Fix bug with double redirect

- jest.config.ts
Set Jest config `workerIdleMemoryLimit` to fix memory leak issue:  https://jestjs.io/docs/configuration/#workeridlememorylimit-numberstring
> Set Jest config workerIdleMemoryLimit

- client/src/services/userServices.ts
- client/src/utils/api.ts
Requestin datan tyypin antaminen on kömpelöä `axios` oman tyypityksen mukaan. Tehdään oma versio, mikä parantaa tyyppien passaamista. Tässä on aikaisemmin ollut aukko, että requestin tyyppiä ei ole käytetty clientin päässä vaikka aivan hyvin voisi.
Ennen:
```ts
const response = await api.post<PostUserResponse, AxiosResponse<PostUserResponse>, PostUserRequest>(
ApiEndpoint.USERS,
{
username,
password,
serial,
}
);
```
Jälkeen:
```ts
const response = await api.post<PostUserResponse, PostUserRequest>(
ApiEndpoint.USERS,
{
username,
password,
serial,
}
);
```
> Improve axios type usage

- .github/workflows/nodejs.yml
* Cache yarn dependencies
* `yarn install`: 1m13s -> 19s
* Cache MongoDB binary
* `yarn test`: 1m35s -> 1m32s
> Cache dependencies

- server/package.json
- server/src/config.ts
- server/src/utils/logger.ts
- server/src/utils/sentry.ts
- shared/config/sharedConfig.ts
- yarn.lock
* Aikaisemmin Sentryyn lähetettiin vain virheet mitä ei otettu kiinni. Lähetetään mieluummin kaikki virheet.
* Poistetaan `winston-daily-rotate-file`: ei ole tarvetta lokittaa levylle.  App Runner koostaa lokit konsolista ja kehittäessä käytetään konsolia.
* Kun kirjoitetaan lokia prod/staging-ympäristöissä, käytetään JSON-formaattia
* Sentryn init-funktioille piti erikseen passata asetus, että ei lokiteta virheitä konsoliin, kun ne lähetetään Sentryyn. `winston` hoitaa konsoliin tulevat lokit.
> Sent caught errors to Sentry and use JSON format on prod/staging

- docker/docker-compose.yml
- package.json
- server/src/test/setupTests.ts
* Update to MongoDB 6.0.6
* Shared free MongoDB Atlas instance was updated to 6.0.6
> Update to MongoDB 6.0.6

- client/vitest.config.ts
- server/vitest.config.ts
Fix `vitest` timeout: enough time to download mongodb binary
> Fix vitest timeout

- .eslintrc.js
- client/.eslintrc.js
- client/src/index.tsx
Disallow `react` default import since we don't need to import `React` on imports
> Disallow react default import

- shared/config/sharedConfig.ts
Remove signup always open from PFS megagame
> Remove signup always open from PFS megagame

- server/src/features/player-assignment/padg/utils/runPadgAssignment.ts
- server/src/features/player-assignment/random/utils/getRandomAssignEvents.ts
- server/src/features/player-assignment/random/utils/runRandomAssignment.ts
- server/src/features/player-assignment/runAssignment.test.ts
- server/src/features/player-assignment/runAssignmentPadg.test.ts
- server/src/features/player-assignment/runAssignmentRandom.test.ts
- server/src/features/player-assignment/utils/getEvents.ts
- server/src/features/player-assignment/utils/saveUserSignupResults.ts
- server/src/features/signup/signupRepository.test.ts
- server/src/features/signup/signupRepository.ts
* Don't remove signups from moved program items
* Save all assignment signups at once using `saveSignups`
* If for some buggy reson there are more signups than seats in program item, give error and limit attendee count
> Don't remove signups from moved program items

- client/package.json
- server/src/features/sentry-tunnel/sentryTunnelController.ts
- yarn.lock
Rollback  `@sentry/react` version `7.68.0` -> `7.69.0` to fix regression with sending tunnel data to backend: https://github.com/getsentry/sentry-javascript/issues/9047
> Rollback sentry-react version to fix regression

- client/src/index.tsx
Ignore Sentry error caused by Outlook scanning links
https://github.com/getsentry/sentry-javascript/issues/3440
> Ignore Sentry error caused by Outlook scanning links

- server/src/utils/instrument.ts
- server/src/utils/logger.ts
Disable `winston-transport-sentry-node` since it doesn't support `sentry-javascript` v8
> Disable winston-transport-sentry-node

- server/src/features/statistics/fixer-helpers/wildFix.ts
- server/src/index.ts
- server/src/test/scripts/loadKompassiDataToDb.ts
- server/src/test/scripts/removeInvalidProgramItems.ts
- server/src/test/scripts/testAssignment.ts
- server/src/test/scripts/testUpdateProgramItemPopularity.ts
- server/src/test/scripts/testVerifyResults.ts
- server/src/test/test-data-generation/parseCliOptions.ts
- server/src/utils/generateSerials.ts
- server/src/utils/server.ts
Fix `logger.error()` calls without message
> Fix logger.error calls without message

- client/src/locales/en.ts
- client/src/locales/fi.ts
- client/src/views/all-program-items/components/AdminActionCard.tsx
- client/src/views/all-program-items/components/AllProgramItemsList.tsx
- client/src/views/all-program-items/components/ProgramItemEntry.tsx
- client/src/views/all-program-items/components/ProgramItemHead.tsx
- client/src/views/all-program-items/components/ProgramItemPage.tsx
- client/src/views/all-program-items/components/SignupsInfo.tsx
- Ei näytetä kahta ristiriitaista UI-viestiä, jos käyttäjä ei ole logannut sisään
- Näytetään julkinen ilmoittautumisen lisätietokysmys ohjelmanumerokortilla
- Siistitään vähän lisätietokysymyksen lisäämisen leiskaa
Monivalintalisätietokysymys:
Tekstimuotoinen lisätietokysymys:
> Fixes to new signups list

- shared/config/sharedConfig.ts
- shared/utils/signupTimes.test.ts
- shared/utils/signupTimes.ts
* Set workshop signups to start 4h before program item
* If workshop starts before 12:00, signup starts previous day at 18:00
> Set workshop signups to start 4h before program item

- client/src/locales/en.ts
- client/src/locales/fi.ts
- client/src/markdown/KonstiFaq.mdx
- client/src/markdown/KonstiInstructions.mdx
- client/src/markdown/components/Expand.tsx
Add expand sections to about pages
> Add expand sections to about pages

- client/src/locales/en.ts
- client/src/locales/fi.ts
- client/src/views/all-program-items/components/EventLogNewAssignment.tsx
Handle new assignment event log item when program item missing
Before:
After:
> Handle new assignment event log item when program item missing

- server/package.json
- server/src/features/assignment/padg/utils/assignPadg.ts
- server/src/features/assignment/random/utils/runRandomAssignment.ts
- server/src/test/test-data-generation/generators/createLotterySignups.ts
- shared/config/serverConfig.ts
> Improve config names

- server/src/features/assignment/runAssignment.ts
- server/src/test/setupTests.ts
- shared/config/eventConfig.ts
- shared/config/eventConfigTypes.ts
- shared/config/serverConfig.ts
Disable `enableRemoveOverlapSignups` for Tracon 2024
> Disable enableRemoveOverlapSignups for Tracon 2024

- server/src/utils/server.ts
Disable `serve-static` acceptRanges since backend doesn't support it
https://www.npmjs.com/package/serve-static#options
> Disable serve-static acceptRanges

- server/src/features/direct-signup/directSignupService.ts
Fix bug where direct signups don't use parent startTime
> Fix bug where direct signups don't use parent startTime
