client/src/config.ts, server/docker-compose.yml, server/server.dockerfile, server/src/config.ts
=> Change server port to 5000

client/package.json, yarn.lock
Remove extract-text-webpack-plugin
=> Remove extract-text-webpack-plugin

client/babel.config.js, client/package.json, client/src/app/App.tsx, client/webpack.config.babel.ts, package.json, yarn.lock
Add React Refresh for hot reloading
=> Add React Refresh for hot reloading

Dockerfile, docker-compose.yml, package.json, server/Dockerfile, server/package.json
Move Docker config to monorepo
=> Move Docker config to monorepo

Dockerfile, README.md, package.json, server/src/test/test-data-generation/runGenerators.ts
Populate DB when Docker starts
=> Populate DB when Docker starts

client/.eslintrc.js
Enable ESLint no-multiple-components
=> Enable ESLint no-multiple-components

.yarnclean
Remove yarnclean file, it's no longer needed as the original issue with styled-components TS types is fixed
=> Remove yarnclean file

client/babel.config.js, client/cypress/docker-compose.yml, client/cypress/integration/login.spec.ts, client/cypress/tsconfig.json, client/package.json
=> Fix Cypress absolute imports

package.json, server/package.json, server/src/api/controllers/test/assignmentController.test.ts, server/src/api/controllers/test/favoriteController.test.ts, server/src/api/controllers/test/feedbackController.test.ts, server/src/api/controllers/test/gamesController.test.ts, server/src/api/controllers/test/groupController.test.ts, server/src/api/controllers/test/hiddenController.test.ts, server/src/api/controllers/test/loginController.test.ts, server/src/api/controllers/test/resultsController.test.ts, server/src/api/controllers/test/settingsController.test.ts, server/src/api/controllers/test/signupController.test.ts, server/src/api/controllers/test/signuptimeController.test.ts, server/src/api/controllers/test/toggleAppOpenController.test.ts, server/src/api/controllers/test/userController.test.ts, server/src/db/mongodb.ts, server/src/index.ts, server/src/utils/closeServer.ts, server/src/utils/test/server.test.ts, yarn.lock
Use ts-node with nodemon and add graceful shutdown
=> Use ts-node with nodemon and add graceful shutdown

server/src/api/apiRoutes.ts, server/src/api/controllers/assignmentController.ts, server/src/api/controllers/favoriteController.ts, server/src/api/controllers/feedbackController.ts, server/src/api/controllers/groupController.ts, server/src/api/controllers/hiddenController.ts, server/src/api/controllers/loginController.ts, server/src/api/controllers/resultsController.ts, server/src/api/controllers/settingsController.ts, server/src/api/controllers/signupController.ts, server/src/api/controllers/signuptimeController.ts, server/src/api/controllers/toggleAppOpenController.ts, server/src/api/controllers/userController.ts, server/src/typings/user.typings.ts, shared/typings/api/games.ts
* Remove Express from controllers and add controller return typings.
* Handle everything Express related in `apiRoutes.ts`.
* This is intermediate step towards better server side separation of concerns.
=> Remove Express from controllers and add controller return typings

client/jest.config.js, server/jest.config.js
Import `shared` folder from `jest` tests
=> Import shared folder from jest tests

server/src/test/setupTests.ts
=> Fail test if error is logged

client/src/services/assignmentServices.ts, client/src/services/favoriteServices.ts, client/src/services/feedbackServices.ts, client/src/services/gamesServices.ts, client/src/services/groupServices.ts, client/src/services/hiddenServices.ts, client/src/services/loginServices.ts, client/src/services/resultsServices.ts, client/src/services/settingsServices.ts, client/src/services/signupServices.ts, client/src/services/signuptimeServices.ts, client/src/services/userServices.ts, client/src/typings/user.typings.ts, client/src/typings/utils.typings.ts, client/src/views/login/loginActions.ts, server/src/api/apiRoutes.ts, server/src/features/signup/signupController.ts, server/src/features/signup/signupService.ts, server/src/features/user/userController.ts, shared/typings/api/errors.ts, shared/typings/api/signup.ts
- Move `ServerError` type to `/shared`
- Add `signup` as separate backend feature
=> Move ServerError to shared and add signup as backend feature

server/src/test/setupTests.ts
Disable test fail on error log
=> Disable test fail on error log

client/.eslintrc.js, server/.eslintrc.js
=> Don't allow disabled tests

server/src/test/test-data-generation/generators/createGames.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/test/test-data-generation/generators/generateTestData.ts, server/src/test/test-data-generation/runGenerators.ts
* Unify test data generation functions
* Set max values for random number generation
=> Unify test data generation functions

server/src/features/player-assignment/assignmentController.ts, server/src/features/player-assignment/runAssignment.ts, server/src/features/player-assignment/test/assignPlayers.test.ts, server/src/utils/cron.ts
Always pass assignment strategy, don't use default value
=> Always pass assignment strategy, don't use default value

server/src/features/player-assignment/test/utils/verifyUserSignups.ts, server/src/features/player-assignment/utils/removeOverlapSignups.ts, server/src/features/player-assignment/utils/saveUserSignupResults.ts
Refactor assignment result related functions
=> Refactor assignment result related functions

.eslintrc.js, client/.eslintrc.js, client/src/app/App.tsx, server/.eslintrc.js, tsconfig.json
Move ESLint rules to top level config file
=> Move ESLint rules to top level config file

client/src/services/favoriteServices.ts, client/src/services/groupServices.ts, client/src/services/loginServices.ts, client/src/services/signupServices.ts, client/src/services/userServices.ts, client/src/typings/group.typings.ts, client/src/typings/user.typings.ts, client/src/views/group/groupActions.ts, client/src/views/login/LoginView.tsx, client/src/views/login/loginActions.ts, client/src/views/my-games/myGamesActions.ts, client/src/views/registration/RegistrationView.tsx, client/src/views/registration/registrationActions.ts, client/src/views/signup/signupActions.ts, server/src/features/feedback/feedbackController.ts, server/src/features/results/resultsController.ts, server/src/features/settings/settingsController.ts, server/src/features/user/userController.ts, server/src/features/user/userRepository.ts, server/src/features/user/userService.ts, server/src/typings/user.typings.ts, shared/typings/api/favorite.ts, shared/typings/api/groups.ts, shared/typings/api/login.ts, shared/typings/api/signup.ts
Type server POST request bodies
=> Type server POST request bodies

package.json, server/src/api/apiRoutes.ts, server/src/features/game/gameUtils.ts, server/src/features/player-assignment/utils/saveUserSignupResults.ts, server/src/features/user/test/userController.test.ts, server/src/features/user/test/userService.test.ts, server/src/features/user/userController.ts, server/src/features/user/userRepository.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, shared/constants/apiEndpoints.ts, shared/typings/api/signup.ts
* New endpoint to add `enteredGame` to user
* New endpoint to delete `enteredGame` from user
=> New endpoints to add and delete enteredGame

server/src/api/apiRoutes.ts, server/src/features/user/entered-game/enteredGameController.ts, server/src/features/user/entered-game/enteredGameService.ts, server/src/features/user/entered-game/test/enteredGameService.test.ts, server/src/features/user/test/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userRepository.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, server/src/test/setupTests.ts, shared/typings/api/signup.ts
* Add post/delete `enteredGame` tests
* Add them to new folder `features/user/entered-game`
=> Add post/delete enteredGame tests

server/src/features/user/entered-game/test/enteredGameService.test.ts
Improve enteredGame API tests: check values from DB after request
=> Improve enteredGame API tests: check values from DB after request

client/src/components/Header.tsx, client/src/components/Navigation.tsx, client/src/globalStyle.ts, client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx
=> Feature/frontpage UI enchantments

.eslintrc.js, client/.eslintrc.js, client/src/app/App.test.tsx, client/src/app/Routes.test.tsx, client/src/utils/getUpcomingGames.ts, client/src/views/all-games/AllGamesView.test.tsx, client/src/views/helper/HelperView.test.tsx, client/src/views/my-games/MyGamesView.test.tsx, client/src/views/results/ResultsView.test.tsx, package.json, server/.eslintrc.js, server/src/features/player-assignment/group/utils/runGroupAssignment.ts, server/src/features/player-assignment/utils/getList.test.ts, server/src/features/user/userService.ts, server/src/utils/logger.ts, yarn.lock
=> Adjust ESLint rules

package.json, server/package.json, server/tsconfig.json, yarn.lock
Replace nodemon with ts-node-dev
=> Replace nodemon with ts-node-dev

client/jest.config.ts, package.json, server/jest.config.ts, yarn.lock
Update to Jest 27: https://jestjs.io/blog/2021/05/25/jest-27
=> Update to Jest 27

client/.eslintrc.js, client/src/app/Routes.tsx, client/src/components/Accordion.tsx, client/src/components/LanguageSelector.tsx, client/src/views/admin/AdminView.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/helper/HelperView.tsx, client/src/views/my-games/MyGamesView.tsx
Enable ESLint rule no-useless-fragment
=> Enable ESLint rule no-useless-fragment

server/src/features/feedback/feedbackController.test.ts, server/src/features/game/gamesController.test.ts, server/src/features/player-assignment/assignmentController.test.ts, server/src/features/results/resultsController.test.ts, server/src/features/settings/settingsController.test.ts, server/src/features/user/entered-game/enteredGameService.test.ts, server/src/features/user/userController.test.ts, server/src/index.ts, server/src/utils/closeServer.ts, server/src/utils/server.test.ts, server/src/utils/startServer.ts
=> Start server on startServer()

server/src/db/mongodb.ts, server/src/features/feedback/feedbackController.test.ts, server/src/features/game/gamesController.test.ts, server/src/features/player-assignment/assignmentController.test.ts, server/src/features/results/resultsController.test.ts, server/src/features/settings/settingsController.test.ts, server/src/features/user/entered-game/enteredGameService.test.ts, server/src/features/user/userController.test.ts, server/src/index.ts, server/src/utils/closeServer.ts, server/src/utils/server.test.ts
Don't pass connString to db.close()
=> Don't pass connString to db.close()

server/package.json, server/src/db/mongodb.ts, server/src/index.ts, server/src/utils/closeServer.ts, server/src/utils/startServer.ts, yarn.lock
* Express server cleanup
* Remove `body-parser`
=> Express server cleanup

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/results/ResultsView.tsx, client/src/views/results/components/AlgorithmResults.tsx, client/src/views/results/components/AlgorithmResultsList.test.tsx, client/src/views/results/components/AlgorithmResultsList.tsx, client/src/views/results/components/DirectResults.tsx
First version of direct results
=> First version of direct results

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/registration/components/RegistrationForm.tsx
Lisätään teksti "Huomaa, että käyttäjänimi on julkinen KAIKILLE käyttäjille" varoitus rekisteröintikenttään ja sama englanniksi
=> warning added to registration field

.eslintrc.js, server/src/features/player-assignment/random/utils/getRandomAssignEvents.ts, server/src/test/__mocks__/generate-serial-number.ts, server/src/typings/padgRandomAssign.typings.ts
Enforce PascalCase to TS interface names
=> Enforce PascalCase to TS interface names

client/.eslintrc.js, client/src/utils/getJWT.ts, client/src/utils/localStorage.ts, client/src/views/admin/AdminView.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/results/components/DirectResults.tsx
* Fix `DirectResult` React key errors
* Enable `no-console` ESLint rule on front
=> Fix React key errors and enable no-console

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/getUpcomingGames.ts, client/src/views/results/ResultsView.tsx, client/src/views/results/components/DirectResults.tsx
* Lisätään tulosnäkymään valinta, näytetäänkö tulevat pelit vai kaikki pelit
* Lisätty maininta "pelissä ei ole yhtään pelaajaa"
=> Add time toggle to results

client/.eslintrc.js, client/.stylelintrc.js, client/package.json, client/src/components/Accordion.tsx, client/src/components/Button.tsx, client/src/globalStyle.ts, client/src/views/admin/AdminView.tsx, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/results/components/AlgorithmResultsList.tsx, client/src/views/results/components/DirectResults.tsx, client/src/views/signup/components/SignupActionButtons.tsx, client/src/views/signup/components/SignupTimeButtons.tsx, shared/config/sharedConfig.ts, yarn.lock
* Add `Button` component
* Change `stylelint-config-standard` to `stylelint-config-recommended` which works better with `styled-components`
=> Add Button component

client/.stylelintrc.js, client/src/components/Button.tsx, client/src/components/FormField.tsx, client/src/components/Header.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/components/Navigation.tsx, client/src/components/UserNavigation.tsx, client/src/globalStyle.ts, client/src/theme.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/group/GroupView.tsx, client/src/views/signup/components/DropRow.tsx, client/src/views/signup/components/SignupTimeButtons.tsx
* Change default button background color to white 
* Use `background` shorthand instead of `background-color`
=> Change default button background color and use background shorthand

client/src/components/Accordion.test.tsx, client/src/components/Accordion.tsx, client/src/components/Paragraph.tsx, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/results/components/DirectResults.tsx, client/src/views/signup/components/SignupInfo.tsx
=> Refactor accordion component

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/results/components/DirectResults.tsx
=> Results view styling

client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/signup/components/SignupList.tsx, server/src/features/player-assignment/utils/getList.test.ts, server/src/features/player-assignment/utils/saveUserSignupResults.ts, server/src/features/results/resultsRepository.ts, server/src/features/user/entered-game/enteredGameService.test.ts, server/src/features/user/userRepository.ts, server/src/features/user/userSchema.ts, server/src/test/mock-data/mockResults.ts, server/src/test/mock-data/mockUser.ts, server/src/test/test-data-generation/generators/createSignups.ts, shared/typings/api/signup.ts, shared/typings/models/user.ts
Add support for signup message
=> Add support for signup message

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/admin/AdminView.tsx, client/src/views/admin/components/HiddenGamesList.test.tsx, client/src/views/admin/components/HiddenGamesList.tsx, client/src/views/admin/components/SignupMessageList.test.tsx, client/src/views/admin/components/SignupMessageList.tsx, client/webpack.config.babel.ts
* Add signup messages to admin view
* Rename `Hidden` to `HiddenGamesList`
=> Add signup messages to admin view

server/src/features/user/entered-game/enteredGameService.ts, server/src/features/user/userRepository.ts, shared/typings/api/signup.ts
=> Return enteredGame on signup

server/package.json, server/src/features/statistics/dataFixer.ts, server/src/features/statistics/statGenerator.ts, server/src/test/test-data-generation/runGenerators.ts, yarn.lock
=> Update to commander 8.0.0

server/src/features/user/userRepository.ts, server/src/test/test-data-generation/generators/createSignups.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/test/test-data-generation/runGenerators.ts
Simplify creation function calls and add removeSignup()
=> Simplify creation function calls and add removeSignup()

server/src/features/settings/settingsRepository.ts, server/src/features/user/userRepository.ts, server/src/test/test-data-generation/generators/createEnteredGames.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/runGenerators.ts
* Add `enteredGame` and `signupMessage` generators
* `enteredGame` are generated by passing `-e` flag to `generate-data`: `yarn generate-data -e`
* `signupMessage` are generated when generating `enteredGame`
=> Add enteredGame and signupMessage generators

client/src/utils/icons.ts, client/src/views/results/components/DirectResults.tsx, server/src/test/test-data-generation/generators/createEnteredGames.ts
* Add toggle to show and hide signup messages
* Import `far` icons by name
* Generate signup message answers with `faker`
=> Add toggle to show and hide signup messages

.eslintrc.js, client/src/app/Routes.test.tsx, client/src/views/all-games/components/AllGamesList.test.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/login/components/LoginForm.test.tsx, client/src/views/login/loginSlice.ts, client/src/views/logout/LogoutView.test.tsx, client/src/views/my-games/myGamesSlice.ts, client/src/views/registration/components/RegistrationForm.test.tsx, client/src/views/results/components/AlgorithmResults.tsx, client/src/views/results/components/DirectResults.tsx, client/src/views/results/resultsSlice.ts, client/src/views/signup/signupSlice.ts, server/src/features/feedback/feedbackController.test.ts, server/src/features/game/gamesController.test.ts, server/src/features/player-assignment/assignmentController.test.ts, server/src/features/results/resultsController.test.ts, server/src/features/settings/settingsController.test.ts, server/src/test/test-data-generation/generators/createEnteredGames.ts, server/src/utils/server.test.ts, server/src/utils/server.ts
* Re-enable now fixed import/order ESLint rule
* Fix errors
=> Re-enable now fixed import/order ESLint rule

client/src/config.ts, client/src/typings/config.typings.ts, client/src/utils/store.ts, client/webpack.config.babel.ts
* Change event year to `2021`
* Rename config `reduxTrace` -> `enableReduxTrace`
=> Change event year and rename config

babel.config.js, server/src/features/user/entered-game/enteredGameService.test.ts, shared/constants/validation.ts, shared/typings/api/signup.ts
* Add backend validation for signup message length
* Fix `babel-plugin-module-resolver` path mapping for shared folder
=> Add backend validation for signup message length

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/registration/components/RegistrationForm.tsx
Add info message about Discord username
=> Add info message about Discord username

client/src/app/App.tsx, client/src/app/Routes.test.tsx, client/src/app/Routes.tsx, client/src/components/UserNavigation.tsx, client/src/locales/fi.json
* Show login when app is closed
* Add role redirects: admin user to admin view, helper user to helper view
=> Show login when app is closed and add role redirects

client/src/app/Routes.tsx, server/package.json, server/src/test/test-data-generation/generators/createUsers.ts, server/src/utils/initializeDatabase.ts
* Add script to initialize db
* Revert user role specific redirect, it didn't feel right
=> Add script to initialize db

client/src/utils/loadData.ts, client/src/views/login/LoginView.tsx, client/src/views/login/loginThunks.ts, client/src/views/registration/RegistrationView.tsx, client/src/views/registration/registrationThunks.ts, server/src/features/user/userService.ts, server/src/utils/jwt.ts
* Fix session expiration error
* Set expire to 14d
* Refactor how login and registration error codes are handled
=> Fix session expiration and set expire to 14d

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/validate.ts, client/src/views/registration/components/RegistrationForm.tsx, server/src/api/validation.ts, server/src/features/user/userController.ts, shared/constants/validation.ts
* Add min and max length to username and password
* Add frontend validation
* Add backend validation: some validations existed but add the rest
=> Add value too long and too short messages to registration form

Dockerfile, package.json
* Update docker image node version
* `docker-compose:stop` script: Add filepath to `docker-compose.yml`
=> Update docker image node version

client/src/services/loginServices.test.ts, client/src/services/loginServices.ts, client/src/utils/loadData.ts, client/src/views/login/LoginView.tsx, client/src/views/login/loginThunks.ts, server/src/api/apiRoutes.ts, server/src/features/user/session-restore/sessionRestoreController.test.ts, server/src/features/user/session-restore/sessionRestoreController.ts, server/src/features/user/session-restore/sessionRestoreService.ts, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, shared/constants/apiEndpoints.ts, shared/typings/api/login.ts
Separate login and session restore
=> Separate login and session restore

server/src/features/user/session-restore/sessionRestoreController.test.ts, server/src/features/user/userController.test.ts
Run test cleanup in finally block to make sure test is properly terminated
=> Run test cleanup in finally block to make sure test is properly terminated

client/src/theme.ts
=> Change button background for bigger contrast

client/src/views/login/loginThunks.ts
=> Load user data on login

client/src/views/helper/HelperView.tsx
Hide results on helper view when using direct signup
=> Hide results on helper view when using direct signup

client/src/locales/en.json, client/src/locales/fi.json, server/src/api/apiRoutes.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts
=> Allow to change password using username

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/results/components/DirectResults.tsx
- Filtteröinti pelin nimellä
- Filtteröinti käyttäjänimellä
=> Add filtering to results view

client/src/components/FirstLogin.tsx, client/src/components/Header.tsx, client/src/locales/en.json, client/src/locales/fi.json
=> Show message on first login

server/src/test/scripts/loadKompassiDataToDb.ts
=> Add missing file

server/src/utils/kompassiGameMapper.ts, server/src/utils/updateGames.ts, shared/constants/kompassiProgramType.ts
Add Kompassi program type enum
=> Add Kompassi program type enum

client/src/views/all-games/components/GameEntry.tsx
Show first description sentences if blurb is missing
=> Show first description sentences if blurb is missing

client/src/views/all-games/components/GameEntry.tsx
Show game system only if it is available
=> Show game system only if it is available

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/AllGamesView.tsx
=> Add larp tag filter

client/package.json
Remove duplicate `require` dependency
=> Remove duplicate require dependency

.gitignore, .prettierignore, client/src/views/my-games/components/GamesByStartTimes.test.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/ResultsByStartTimes.test.tsx, client/src/views/my-games/components/ResultsByStartTimes.tsx
- Peru-painike lisätty MyGamesissa näytettävien pelien rinnalle
- Husky loi jonkin _ / kansion linuxissa niin gitignoroin sen
- Miusta peruuta-painikkeen jälkeen olisi hyvä että tulis samanlainen varmista-dialogi kuin ilmoittautumisen yhteydessä, mutta tein tän nyt samalla tavalla kuin AllGamesissa, jotta ei ole sekavaa
=> Added cancel button to my games

client/src/components/Header.tsx, client/src/config.ts, client/src/test/test-components/TestTimeSelector.tsx, package.json
* Update convention start time
* Rename component `TimeSelector` -> `TestTimeSelector`
* Improve `populate-db:kompassi` script by downloading game data first
=> Update convention start time and rename time selector component

package.json
Fix populate-db:kompassi script
=> Fix populate-db:kompassi script

server/src/config.ts
Adjust cron configs with shared configs
=> Adjust cron configs with shared configs

client/src/views/all-games/components/AllGamesList.tsx
Hide signup time on direct signup
=> Hide signup time on direct signup

client/src/views/all-games/components/DirectSignupForm.tsx
=> Hide signup button if game is full

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx
=> Show game expected length

server/src/utils/cron.ts
=> Fix game update cronjob

client/src/config.ts, client/src/views/all-games/AllGamesView.tsx
=> Enable revolving door games

client/src/locales/en.json, client/src/locales/fi.json
Update main title to include larps
=> Update main title to include larps

server/src/utils/cron.ts, server/src/utils/updateGames.ts
Handle promise propely if Kompassi update fails
=> Handle promise propely if Kompassi update fails

client/src/utils/getTime.ts
Fix bug with getTime() function
=> Fix bug with getTime() function

client/src/app/App.tsx, client/src/components/Header.tsx
Move closed message to end of header
Before
After
=> Move closed message to end of header

client/src/app/Routes.tsx
* Redirect helper login to helper view if app closed
* Allow using helper view if app is closed
=> Redirect helper login to helper view if app closed

client/src/app/Routes.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/utils/checkUserGroup.ts
Allow normal use of closed app as admin or helper
=> Allow normal use of closed app as admin or helper

client/src/views/all-games/components/GameInfo.tsx
Don't show empty content warning `-`
=> Don't show empty content warning "-"

client/src/locales/fi.json, client/src/views/admin/AdminView.tsx, client/src/views/admin/components/SignupMessageList.test.tsx, client/src/views/admin/components/SignupMessageList.tsx
Show game title on admin signup message list
=> Show game title on admin signup message list

client/.stylelintrc.js, client/src/views/results/components/DirectResults.tsx
Improve results list ordering and add program type
**Before**
**After**
=> Improve results list ordering and add program type

client/src/utils/favorite.ts, server/src/features/user/userController.ts, server/src/features/user/userRepository.ts, shared/typings/api/favorite.ts
Send only gameid to saveFavorite
=> Send only gameid to saveFavorite

client/src/components/Button.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/services/userServices.ts, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/PasswordManagement.test.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, server/src/api/apiRoutes.ts, server/src/config.ts, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts, server/src/typings/config.typings.ts, server/src/utils/jwt.ts, shared/constants/apiEndpoints.ts
Allow chancing password from login screen
=> Allow chancing password from login screen

client/src/theme.ts, client/src/views/all-games/components/EnterGameForm.tsx
=> Highlight signup confirmation button

client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx
=> Load games after entering games or removing signup

client/src/locales/en.json, client/src/locales/fi.json
=> Update Discord info text

client/src/locales/en.json, client/src/locales/fi.json, client/src/services/userServices.test.ts, client/src/services/userServices.ts, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/helper/components/PasswordManagement.test.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/MyGamesView.tsx, server/src/api/apiRoutes.ts, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts, server/src/utils/authHeader.ts, server/src/utils/jwt.ts, shared/constants/apiEndpoints.ts, shared/typings/api/login.ts
Allow changing password from MyGames view
=> Allow changing password from MyGames view

client/src/views/all-games/AllGamesView.tsx
=> Add age restriction filters

client/src/views/all-games/components/CancelSignupForm.tsx
Bug: Load games after signup cancel
=> Bug: Load games after signup cancel

client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx
* Refactor `AllGamesList` to use `.map()`
* Remove unused classNames
=> Refactor AllGamesList and minor cleanup

client/package.json, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameListTitle.tsx, yarn.lock
* Show `AllGames` title shadow only when title element is visible
* Split `GameListTitle.tsx` to own component
=> Show AllGames title shadow only when title element is visible

client/src/locales/en.json, client/src/views/registration/components/RegistrationForm.tsx
=> Fix double comma

client/src/config.ts
=> Adjust convention start time

client/src/views/results/components/DirectResults.tsx
=> Sort results

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/components/LoginForm.tsx, client/src/views/registration/components/RegistrationForm.tsx
=> Add Discord instructions

client/src/views/results/components/DirectResults.tsx
Filter hidden games from results view
=> Filter hidden games from results view

client/package.json, client/src/utils/i18n.ts, yarn.lock
Remove deprecated `i18next-xhr-backend`
=> Remove deprecated i18next-xhr-backend

client/src/globalStyle.ts, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/GameInfo.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/components/HelperResultsList.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/ResultsByStartTimes.tsx, client/src/views/my-games/components/SignupsByStartTimes.tsx, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/results/components/ResultsByGameTitle.tsx, client/src/views/signup/components/DropRow.tsx, client/src/views/signup/components/SignupActionButtons.tsx
* Remove global CSS class name styles and replace with styled-components
* small, bold, italic, no-wrap, break-long
=> Remove global CSS class name styles

client/src/components/Button.tsx, client/src/components/LanguageSelector.tsx, client/src/views/group/GroupView.tsx, client/src/views/signup/components/SignupTimeButtons.tsx
Remove className props from Button and LanguageSelector
=> Remove className props from Button and LanguageSelector

client/src/components/TimesDropdown.tsx, client/src/index.tsx, client/src/test/test-components/TestTimeSelector.tsx, client/src/views/admin/AdminView.tsx, client/src/views/admin/components/HiddenGamesList.tsx, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/HelperResultsList.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/LoginView.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/MyEnteredList.tsx, client/src/views/my-games/components/MyFavoritesList.tsx, client/src/views/my-games/components/MySignupsList.tsx, client/src/views/my-games/components/ResultsByStartTimes.tsx, client/src/views/my-games/components/SignupsByStartTimes.tsx, client/src/views/registration/RegistrationView.tsx, client/src/views/results/components/AlgorithmResults.tsx, client/src/views/results/components/AlgorithmResultsList.tsx, client/src/views/results/components/DirectResults.tsx, client/src/views/results/components/ResultsByGameTitle.tsx, client/src/views/signup/SignupView.tsx, client/src/views/signup/components/SignupActionButtons.tsx
=> Remove unused classNames

client/src/views/admin/AdminView.tsx, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/GameInfo.tsx, client/src/views/group/GroupView.tsx, client/src/views/results/components/ResultsByUsername.tsx, client/src/views/signup/components/DropRow.test.tsx, client/src/views/signup/components/DropRow.tsx
=> Remove remaining classNames

client/src/views/all-games/components/GameDetails.tsx
=> Fix TS error

client/src/utils/localStorage.ts, client/src/utils/store.ts
=> Fix TS errors

client/cypress/support/cypressUtils.ts, client/src/components/Button.tsx, client/src/components/Navigation.tsx, client/src/components/UserNavigation.tsx, client/src/views/login/components/LoginForm.tsx
Rename `data-testkey` to `data-testid`
=> Rename data-testkey to data-testid

server/package.json, server/src/features/statistics/fixer-helpers/dataAnonymizer.ts, server/src/test/test-data-generation/generators/createEnteredGames.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/test/test-data-generation/generators/createSignups.ts, server/src/test/test-data-generation/generators/createUsers.ts, yarn.lock
=> Replace faker with fork

client/package.json, client/src/app/App.tsx, client/src/app/Routes.test.tsx, client/src/app/Routes.tsx, client/src/views/all-games/components/GameDetails.test.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/logout/LogoutView.test.tsx, client/src/views/logout/LogoutView.tsx, yarn.lock
* Update to `react-router` v6
* https://reactrouter.com/docs/en/v6/upgrading/v5
=> Update to react-router v6

client/src/components/FirstLogin.tsx, client/src/components/Header.tsx, client/src/config.ts, client/src/test/test-components/TestTimeSelector.tsx, client/src/typings/config.typings.ts, client/src/utils/timeFormatter.ts, server/src/config.ts, server/src/features/player-assignment/runAssignment.test.ts, server/src/test/scripts/testAssignPlayers.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/typings/config.typings.ts, shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts
* Update Ropecon 2022 convention time
* Move convention details to shared settings
=> Update Ropecon 2022 convention time

client/src/components/Button.tsx
* Fix Button visual regression
* `styled-components` styling requires `className` prop: https://styled-components.com/docs/advanced#styling-normal-react-components
=> Fix Button visual regression

server/src/features/settings/settingsSchema.ts
=> Set default signup strategy

server/src/config.ts, server/src/features/settings/settingsController.ts
Use correct env variable to limit api
=> Use correct env variable to limit api

server/src/test/test-data-generation/generators/createGames.ts
Fix data generation game category
=> Fix data generation game category

client/src/components/Dropdown.tsx, client/src/test/test-components/SignupStrategySelector.tsx
=> Add loading state to dropdown

client/src/config.ts, client/src/typings/config.typings.ts, client/src/utils/getOpenStartTimes.ts, client/src/utils/timeFormatter.ts, client/src/views/my-games/utils/getMissedSignups.ts, shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts
Move signup time variables to shared config
=> Move signup time variables to shared config

shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts
Add two phase signup time settings
=> Add two phase signup time settings

server/src/api/apiRoutes.ts, server/src/db/mongoosePlugins.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsController.ts, server/src/features/settings/settingsRepository.ts, server/src/features/settings/settingsService.ts, server/src/utils/server.ts, shared/typings/api/settings.ts, shared/typings/models/settings.ts
* Add POST settings endpoint
* Add global `mongoose` plugin to strip `_id` and `__v` when calling `toJSON()`
=> Add POST settings endpoint

server/src/api/apiRoutes.ts, server/src/test/test-settings/testSettingsController.test.ts, server/src/test/test-settings/testSettingsController.ts, server/src/test/test-settings/testSettingsRepository.ts, server/src/test/test-settings/testSettingsSchema.ts, server/src/test/test-settings/testSettingsService.ts, server/src/utils/initializeDatabase.ts, server/src/utils/server.ts, shared/constants/apiEndpoints.ts, shared/test-typings/api/testSettings.ts, shared/test-typings/models/testSettings.ts
Add test settings endpoints
* `GET TEST_SETTINGS_ENDPOINT`
* `POST TEST_SETTINGS_ENDPOINT`
* Body:
```
{
testTime: "2021-07-16T14:28:01.316Z",
}
```
=> Add test settings endpoint

client/src/test/test-components/TestTimeSelector.tsx, client/src/test/test-settings/testSettingsServices.ts, client/src/test/test-settings/testSettingsSlice.ts, client/src/test/test-settings/testSettingsThunks.ts, client/src/typings/redux.typings.ts, client/src/utils/getTime.ts, client/src/utils/store.ts, client/src/views/admin/adminSlice.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/results/ResultsView.tsx, client/src/views/signup/SignupView.tsx
Hook test time dropdown to backend
=> Hook test time dropdown to backend

client/src/app/App.test.tsx, client/src/test/test-settings/testSettingsServices.ts, client/src/test/test-settings/testSettingsThunks.ts, client/src/utils/loadData.ts, server/src/test/test-settings/testSettingsRepository.ts
Load test settings with other data
=> Load test settings with other data

docker/docker-compose.yml, server/package.json
=> Update to mongodb 5

.gitignore, package.json
=> Enable eslint cache

client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameListTitle.tsx, server/src/features/game/gameUtils.ts, server/src/features/game/gamesService.ts, shared/typings/models/game.ts
=> Add support for DIRECT+ALGORITHM signup strategy to frontend

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/components/LoginForm.tsx, client/src/views/registration/components/RegistrationForm.tsx
Fix forms enter submit and show required lengths
=> Fix forms enter submit and show required lenghts

client/src/locales/en.json, client/src/locales/fi.json, client/src/test/test-components/SignupStrategySelector.tsx, server/src/features/game/gameUtils.ts, shared/config/sharedConfig.types.ts
Rename direct-algorithm to algorithm-and-direct
=> Rename direct-algorithm to algorithm-and-direct

client/src/utils/validate.ts, client/src/views/helper/components/ChangePasswordForm.tsx
Fix ChangePasswordForm min/max value in error
=> Fix ChangePasswordForm min/max value in error

client/src/views/my-games/MyGamesView.tsx
Show selected games with algorithm-and-direct
=> Show selected games with algorithm-and-direct

client/src/components/Header.tsx, client/src/components/Navigation.tsx
Fix navigation menu positioning
=> Fix navigation menu positioning

client/package.json, client/src/app/AppRoutes.tsx, yarn.lock
Fix route bug when app is closed
=> Fix route bug when app is closed

client/playwright/playwright.config.ts, client/playwright/tests/add-favorite.spec.ts, client/src/components/LoggedInUserNavigation.tsx, client/src/typings/redux.typings.ts, client/src/utils/favorite.ts, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/MyFavoritesList.tsx, client/src/views/my-games/myGamesSlice.ts, client/src/views/my-games/myGamesTypes.ts, server/src/features/settings/settingsUtils.ts, server/src/features/statistics/fixer-helpers/gameIdFix.ts, server/src/features/user/userController.ts, server/src/features/user/userRepository.ts, server/src/features/user/userSchema.ts, server/src/features/user/userService.ts, server/src/typings/user.typings.ts, shared/typings/api/favorite.ts, shared/typings/api/users.ts, shared/typings/models/user.ts
Refactor favorite game to string array and add Playwright test
=> Refactor favorite game to string array and add Playwright test

client/src/services/groupServices.test.ts, client/src/services/groupServices.ts, client/src/utils/getUpcomingGames.ts, client/src/views/group/GroupView.tsx, client/src/views/group/components/GroupMembersList.tsx, client/src/views/group/groupThunks.ts, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/MySignupsList.test.tsx, client/src/views/my-games/components/MySignupsList.tsx, client/src/views/signup/SignupView.tsx, client/src/views/signup/components/SignupActionButtons.tsx, client/src/views/signup/components/SignupList.test.tsx, client/src/views/signup/components/SignupList.tsx, server/src/features/player-assignment/utils/verifyUserSignups.ts, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts, server/src/test/test-data-generation/generators/createSignups.ts, shared/config/sharedConfig.ts, shared/typings/api/groups.ts
=> Groups code cleanup

client/src/views/all-games/AllGamesView.tsx
Update games after signup strategy change
=> Update games after signup strategy change

client/src/locales/en.json, client/src/locales/fi.json, client/src/test/test-data/testGame.ts, client/src/typings/declarations/react-i18next.d.ts, client/src/utils/getGameTags.ts, client/src/utils/i18n.ts, client/src/views/all-games/components/GameInfo.tsx, client/src/views/group/components/GroupMembersList.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/login/loginThunks.ts, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/registration/registrationThunks.ts, client/src/views/results/components/AlgorithmResultsList.tsx, client/src/views/signup/components/DragAndDropList.tsx, client/src/views/signup/components/SignupActionButtons.tsx, client/src/views/signup/components/SignupList.tsx, server/src/test/mock-data/mockGame.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/typings/game.typings.ts, server/src/utils/kompassiGameMapper.ts, shared/typings/models/game.ts
TS type support for i18next locales
=> TS type support for i18next locales

server/src/features/player-assignment/group/groupAssignPlayers.ts, server/src/features/player-assignment/padg/padgAssignPlayers.ts, server/src/features/player-assignment/random/randomAssignPlayers.ts
Adjust assignment logging level
=> Adjust assignment logging level

client/package.json, package.json, server/package.json, server/src/utils/getGamesFromKompassi.ts, yarn.lock
Replace `request-promise-native` with `axios` on backend
=> Replace request-promise-native with axios on backend

client/webpack.config.babel.ts
Change Webpack sourcemap to eval-source-map
https://webpack.js.org/configuration/devtool/
=> Change Webpack sourcemap to eval-source-map

client/src/components/Error.tsx, client/src/components/Errors.test.tsx
=> Remove unused Error component

client/src/views/admin/AdminView.tsx, server/src/features/results/resultsController.ts, server/src/test/scripts/testAssignPlayers.ts
Cleanup assignment endpoint and test-assign code
=> Cleanup assignment endpoint and test-assign code

client/src/utils/api.ts
Add global Axios error catcher
=> Add global Axios error catcher

client/src/services/assignmentServices.ts, client/src/services/favoriteServices.ts, client/src/services/feedbackServices.ts, client/src/services/gamesServices.ts, client/src/services/groupServices.ts, client/src/services/hiddenServices.ts, client/src/services/loginServices.ts, client/src/services/resultsServices.ts, client/src/services/settingsServices.ts, client/src/services/signupServices.ts, client/src/services/userServices.ts, client/src/test/test-settings/testSettingsServices.ts, client/src/utils/api.ts, client/src/views/login/loginThunks.ts, server/src/features/feedback/feedbackService.ts, server/src/features/game/gamesService.ts, server/src/features/player-assignment/assignmentController.ts, server/src/features/results/resultsService.ts, server/src/features/settings/settingsService.ts, server/src/features/user/entered-game/enteredGameService.ts, server/src/features/user/session-restore/sessionRestoreService.ts, server/src/features/user/userService.ts, server/src/test/test-settings/testSettingsService.ts, shared/typings/api/errors.ts, shared/typings/api/signup.ts
Rename `ServerError` to `ApiError`
=> Rename ServerError to ApiError

server/src/features/settings/settingsSchema.ts, shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts
Add setting `defaultSignupStrategy` and set convention to `live`
=> Add setting defaultSignupStrategy and set convention to live

client/src/locales/en.json, client/src/locales/fi.json, client/src/test/test-settings/testSettingsThunks.ts, client/src/views/helper/components/HelperResultsList.tsx, client/src/views/results/ResultsView.tsx, client/src/views/results/components/AlgorithmResults.tsx, client/src/views/results/components/DirectResults.tsx
Show results for direct signup games in two phase signup
=> Show results for direct signup games in two phase signup

client/src/views/all-games/AllGamesView.tsx
=> Add SelectedView enum

client/src/typings/redux.typings.ts, client/src/utils/loadData.ts, client/src/utils/store.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/group/GroupView.tsx, client/src/views/group/groupSlice.ts, client/src/views/group/groupThunks.ts, client/src/views/login/loginSlice.ts, client/src/views/login/loginThunks.ts, client/src/views/login/loginTypes.ts, client/src/views/my-games/MyGamesView.tsx, client/src/views/signup/SignupView.tsx, client/src/views/signup/components/DragAndDropList.tsx, client/src/views/signup/components/SignupList.tsx
Move group state to own slice:
- `state.login.groupCode` -> `state.group.groupCode`
- `state.login.groupMembers` -> `state.group.groupMembers`
=> Move group state to own slice

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameListTitle.tsx, client/src/views/all-games/components/allGamesUtils.ts
Show group messages on game list
Group member:
Group creator
:
=> Show group messages on game list

client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/group/GroupView.tsx, client/src/views/my-games/components/CancelSignupForm.tsx, client/src/views/my-games/myGamesSlice.ts, client/src/views/my-games/myGamesThunks.ts
Unify myGames reducer function names
=> Unify myGames reducer function names

client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/allGamesUtils.ts
Fix incorrect login in `removeSignedGame()`
=> Fix incorrect login in removeSignedGame

client/src/components/Button.tsx, client/src/components/FirstLogin.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/components/TestValuePicker.tsx, client/src/components/UserNavigation.tsx, client/src/globalStyle.ts, client/src/theme.ts, client/src/views/admin/AdminView.tsx, client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/helper/components/HelperResultsList.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/components/CancelSignupForm.tsx, client/src/views/registration/RegistrationView.tsx, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/results/components/DirectResults.tsx, client/src/views/results/components/ResultsByGameTitle.tsx, client/src/views/results/components/ResultsByUsername.tsx
=> Improve color theme

client/src/components/Accordion.tsx, client/src/components/Button.tsx, client/src/components/FirstLogin.tsx, client/src/theme.ts, client/src/typings/declarations/styled.d.ts, client/src/utils/addOpacity.ts, client/src/utils/rgbToRgba.ts, client/src/views/admin/AdminView.tsx, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/CancelSignupForm.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/ResultsByStartTimes.tsx, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/results/components/AlgorithmResultsList.tsx, client/src/views/results/components/DirectResults.tsx
* Improve button component
* Type styled-components `theme`
* Add utility function `addOpacity()` to convert rgb colors to rgba
=> Improve button component and type styled-components theme

client/src/views/admin/components/SignupMessageList.tsx, client/src/views/results/components/DirectResults.tsx
Filter hidden games from results correctly
=> Filter hidden games from results correctly

client/src/components/ErrorBar.tsx, client/src/components/ErrorMessage.tsx, client/src/typings/redux.typings.ts, client/src/utils/api.ts, client/src/views/admin/adminSlice.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/login/loginThunks.ts, client/src/views/registration/components/RegistrationForm.tsx
* Add `ErrorMessage` component
* Move `group too big` error next to the button
=> Add ErrorMessage component

server/src/test/scripts/testAssignPlayers.ts
Read  test-assign script strategies from enum
=> Read  test-assign script strategies from enum

client/src/utils/api.ts, client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/my-games/myGamesThunks.ts
=> Add game full error

client/src/components/ErrorBar.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/api.ts
=> Add network error

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/loginThunks.ts, client/src/views/my-games/myGamesThunks.ts, client/src/views/registration/registrationThunks.ts, server/src/features/user/entered-game/enteredGameService.ts, shared/typings/api/myGames.ts
Show signup ended error for entered games
=> Show signup ended error for entered games

client/src/views/all-games/components/GameDetails.tsx
Fix back button when navigating to Konsti from outside
=> Fix back button when navigating to Konsti from outside

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/my-games/myGamesThunks.ts, server/src/features/user/signed-game/signedGameService.ts, shared/typings/api/myGames.ts
Show error if signing up using same priority
=> Show error if signing up using same priority

client/src/views/helper/HelperView.tsx
=> Add HelperTool enum

server/package.json, yarn.lock
-Päivitettiin eventassigner-random versiosta 0.2.0 versioon 0.3.0
=> upgrade eventassigner-random

server/src/features/user/signed-game/signedGameService.ts
=> Check duplicate priorities by timeslot

server/src/features/player-assignment/assignmentController.ts, server/src/features/player-assignment/runAssignment.test.ts, server/src/features/player-assignment/utils/saveResults.ts, server/src/index.ts, server/src/test/scripts/testAssignPlayers.ts, server/src/utils/cron.ts
=> Improve cronjob syntax

server/src/config.ts, server/src/typings/config.typings.ts, server/src/utils/cron.ts
=> Improve cron variables

client/src/test/test-components/TestTimeSelector.tsx, server/src/config.ts, server/src/features/player-assignment/assignmentController.ts, server/src/features/player-assignment/runAssignment.test.ts, server/src/features/player-assignment/runAssignment.ts, server/src/features/player-assignment/utils/getDynamicStartingTime.ts, server/src/features/player-assignment/utils/getTime.ts, server/src/test/scripts/testAssignPlayers.ts, server/src/utils/cron.ts
=> Add dynamic assignment time

client/src/components/TestValuePicker.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/test/test-components/TestTimeSelector.tsx, client/src/test/test-components/testComponentUtils.ts, client/src/utils/getPhaseGap.ts, client/src/utils/getTime.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/my-games/myGamesThunks.ts, server/src/features/user/entered-game/enteredGameService.ts, server/src/utils/getPhaseGap.ts, shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts, shared/typings/api/myGames.ts
Add phase gap to frontend and backend
**Frontend**:
**Backend**;
=> Add phase gap to frontend and backend

client/src/components/Header.tsx, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx
* Fix group too big error message position in component tree
* Make sure ? icon and language selector stay next to each other if screen size is smaller
* Don't show `players needed` message with algorithm strategy
=> Fix group too big error, header styling and players needed

shared/config/sharedConfig.ts, shared/config/sharedConfig.types.ts
Move sharedConfig types to sharedConfig file
=> Move sharedConfig types to sharedConfig file

client/src/theme.ts, client/src/views/all-games/components/SignupForm.tsx
Improve disabled priority selection background color
=> Improve disabled priority selection background color

server/src/features/game/gameController.test.ts
Fix test instability by sorting findGames() result
=> Fix test instability by sorting findGames() result

package.json
=> Add update-yarn script

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/group/GroupView.tsx, client/src/views/group/components/GroupCreatorActions.tsx, client/src/views/group/components/GroupMemberActions.tsx, client/src/views/group/components/NotInGroupActions.tsx, client/src/views/group/groupThunks.ts, client/src/views/group/groupUtils.ts, server/src/features/game/gameController.test.ts, server/src/features/player-assignment/utils/removeInvalidSignupsFromUsers.test.ts, server/src/features/player-assignment/utils/removeMovedGamesFromUsers.test.ts, server/src/features/player-assignment/utils/removeOverlapSignups.test.ts, server/src/features/user/group/groupController.test.ts, server/src/features/user/group/groupController.ts, server/src/features/user/group/groupService.ts, server/src/features/user/signed-game/signedGameController.ts, server/src/test/mock-data/mockUser.ts, shared/typings/api/groups.ts
* Cleanup `GroupView* 
* Add group tests
* Move signup deletion to backend
=> Cleanup GroupView, add group tests and move signup deletion to backend

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/my-games/myGamesThunks.ts, server/src/features/user/entered-game/enteredGameService.ts, server/src/features/user/signed-game/signedGameService.ts, server/src/features/user/userUtils.ts, shared/typings/api/myGames.ts
* Pre-signup styling
* Remove signup time check, it doesn't work with current approach where are signed games are submitted at once
=> Pre-signup styling and remove signup time check

client/src/services/myGamesServices.test.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/login/loginThunks.ts, client/src/views/my-games/myGamesThunks.ts, client/src/views/registration/components/RegistrationForm.tsx, client/src/views/registration/registrationThunks.ts, server/src/features/user/entered-game/enteredGameService.ts, server/src/features/user/signed-game/signedGameController.test.ts, server/src/features/user/signed-game/signedGameController.ts, server/src/features/user/signed-game/signedGameService.ts, server/src/features/user/userUtils.ts, shared/typings/api/myGames.ts, shared/utils/getPhaseGap.ts
* Clone Moment objects to prevent mutation
* Some other cleanup
=> Clone Moment objects to prevent mutation

client/src/app/App.tsx, client/src/components/EventTypeSelection.tsx, client/src/components/Header.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/config.ts, client/src/locales/en.json, client/src/locales/fi.json, client/src/typings/config.typings.ts, client/src/typings/redux.typings.ts, client/src/views/admin/AdminView.tsx, client/src/views/admin/adminSlice.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/allGamesUtils.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameInfo.tsx, client/src/views/all-games/components/GameListTitle.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/results/ResultsView.tsx, client/src/views/results/components/DirectResults.tsx, tsconfig.json
=> Add different event types to frontend

client/src/components/ErrorBar.tsx, client/src/components/EventTypeSelection.tsx, client/src/typings/redux.typings.ts, client/src/utils/localStorage.ts
Persist active program type to localStorage
=> Persist active program type to localStorage

client/src/views/my-games/MyGamesView.tsx
=> Add angle icon to change password toggle

README.md, client/src/views/helper/components/PasswordManagement.tsx, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/test/test-data-generation/generators/createEnteredGames.ts, server/src/test/test-data-generation/generators/createSignups.ts, server/src/test/test-data-generation/generators/createUsers.ts
Change `ropetiski` user to `helper`
=> Change ropetiski user to helper

client/src/views/admin/AdminView.tsx, client/src/views/admin/components/HiddenGamesList.tsx, client/src/views/admin/components/SignupMessageList.tsx, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/results/components/DirectResults.tsx
Don't limit to active games on admin and details views
=> Don't limit to active games on admin and details views

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/group/GroupView.tsx
=> Improve group page info texts

.eslintrc.js, client/playwright/tests/add-favorite.spec.ts, client/playwright/tests/login.spec.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameListTitle.tsx, client/src/views/group/GroupView.tsx, client/src/views/group/components/GroupCreatorActions.tsx, client/src/views/group/components/GroupMemberActions.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/login/components/LoginForm.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/registration/components/RegistrationForm.tsx, server/src/db/mongoosePlugins.ts, server/src/features/game-popularity/utils/updateWithAssign.ts, server/src/features/player-assignment/padg/utils/assignPadg.ts, server/src/test/__mocks__/generate-serial-number.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/test/test-data-generation/testDataController.ts
Fix eslint rule no-unused-vars. Seems like default configs were incorrect/broken.
=> Fix eslint rule no-unused-vars

client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, client/src/views/my-games/components/GamesByStartTimes.tsx, client/src/views/my-games/components/MyEnteredList.tsx, client/src/views/my-games/components/ResultsByStartTimes.tsx, client/src/views/my-games/components/SignupsByStartTimes.tsx, client/src/views/my-games/myGamesSlice.ts, client/src/views/my-games/utils/getGroupCreator.ts, client/src/views/my-games/utils/getMissedSignups.ts, client/src/views/my-games/utils/getSignedGames.ts
Use active program type on my games view
=> Use active program type on my games view

server/src/features/game/utils/getGamesFromKompassi.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/test/test-data-generation/generators/createSignups.ts, server/src/test/test-data-generation/runGenerators.ts
Generate data for all program types
=> Generate data for all program types

client/src/views/results/components/DirectResults.tsx
Sort results view alphabetically
=> Sort results view alphabetically

client/src/components/ErrorMessage.tsx, client/src/theme.ts
=> Add some styles to error close button

client/src/views/group/GroupView.tsx
=> Remove duplicate text in group view

client/src/views/group/GroupView.tsx
=> Show group direct signup message only for RPGs

client/src/services/gamesServices.test.ts, client/src/services/gamesServices.ts, client/src/views/admin/AdminView.tsx, client/src/views/all-games/allGamesThunks.ts, server/src/api/apiRoutes.ts, server/src/features/game/gameController.ts, server/src/features/game/gameRepository.ts, server/src/features/game/gameUtils.ts, server/src/features/game/gamesService.ts, server/src/features/user/entered-game/enteredGameRepository.ts, server/src/test/scripts/loadKompassiDataToDb.ts, shared/typings/api/games.ts
* Rename update games functions
* Remove duplicate get game function
=> Rename update games functions and remove duplicate get game function

server/src/features/game/gameController.test.ts, server/src/features/game/gameUtils.ts
Don't return private message answers
=> Don't return private message answers

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, client/src/views/results/components/DirectResults.tsx
=> Handle private questions in UI

client/src/components/Button.tsx
=> Don't wrap button text

client/src/utils/localStorage.ts, client/src/utils/store.ts
Don't reset testSettings and program type on logout
=> Don't reset testSettings and program type on logout

server/src/features/player-assignment/padg/utils/runPadgAssignment.ts, server/src/features/player-assignment/random/utils/runRandomAssignment.ts
Log assign algorithm input if assignment fails
=> Log assign algorithm input if assignment fails

client/src/components/EventTypeSelection.tsx, client/src/locales/en.json, client/src/locales/fi.json, server/src/utils/kompassiGameMapper.ts, shared/typings/models/game.ts
Change boardgame type to tournament and add plurals
=> Change boardgame type to tournament and add plurals

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/LoginView.tsx, client/src/views/registration/RegistrationView.tsx
Remove Discord guides and term 'game' from couple of places
=> Remove Discord guides and term 'game' from couple of places

client/src/views/all-games/components/GameEntry.tsx
Separate signed and entered games when showing disabled or selected games
=> Separate signed and entered games when showing disabled or selected games

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/loadData.ts, client/src/views/helper/HelperView.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, server/src/test/test-data-generation/generators/createEnteredGames.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/runGenerators.ts
* Add search field to private signup messages
* Improve signup message and entered games seeding
=> Add search field to private signup messages and improve seeding

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/api.ts, server/package.json
=> Improve API error messages

client/src/app/App.tsx
Don't show program type selection if Konsti is closed
=> Don't show program type selection if Konsti is closed

client/jest.config.ts, server/jest.config.ts
=> Jest transpile-only

server/src/config.ts, server/src/utils/kompassiGameMapper.ts, shared/typings/models/kompassiGame.ts
Use Ropecon 2022 Kompassi data
=> Use Ropecon 2022 Kompassi data

server/src/features/game/utils/getGamesFromKompassi.ts, server/src/utils/kompassiGameMapper.ts, shared/typings/models/kompassiGame.ts
=> Fix tournament program types

client/src/views/helper/components/PrivateSignupMessages.tsx
Sort private question answers by `startTime`
=> Sort private question answers by startTime

client/src/index.tsx, client/src/utils/getUpcomingGames.ts, client/src/views/admin/components/SignupQuestionList.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, server/src/features/game/utils/getGamesFromKompassi.ts, server/src/test/test-data-generation/generators/createGames.ts, shared/typings/models/kompassiGame.ts
Show myGames signups in column, not row
=> Show myGames signups in column, not row

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/LoginView.tsx
Add registration link to login page
=> Add registration link to login page

client/src/app/AppRoutes.tsx, client/src/views/login/LoginView.tsx, client/src/views/login/components/LoginForm.tsx
Return to original page after login
=> Return to original page after login

client/src/views/all-games/AllGamesView.tsx, server/src/utils/kompassiGameMapper.ts, shared/typings/models/game.ts
=> Update tags for Ropecon 2022

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/hooks.ts, client/src/views/all-games/AllGamesView.tsx
* Add search field to game list
* Add `useDebounce` hook: https://usehooks-ts.com/react-hook/use-debounce
=> Add search field to game list

client/src/utils/hooks.ts
Add link to debounce hook origin
=> Add link to debounce hook origin

client/src/app/App.tsx, client/src/components/Navigation.tsx, client/src/components/TestValuePicker.tsx
Move test value picker to navigation menu
=> Move test value picker to navigation menu

client/src/views/all-games/components/GameEntry.tsx, client/src/views/my-games/components/SignupsByStartTimes.tsx
Some discussion: https://stackoverflow.com/questions/46965309/react-functional-component-calling-as-function-vs-as-component
=> Call component as component, not function

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx
Allow pre-signup only for correct time slots
=> Allow pre-signup only for correct time slots

client/src/theme.ts, client/src/views/results/components/DirectResults.tsx
=> Move results under the fold

client/src/views/group/components/NotInGroupActions.tsx
=> Disable create group button if user has signed in games

client/src/views/my-games/components/EnteredGameRow.tsx
=> Fix entered game click area

client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/views/all-games/components/EnterGameForm.tsx
=> Remove user from group when entering game

client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/views/all-games/components/GameEntry.tsx
=> Move tags under title

client/package.json, client/src/components/Input.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/hooks.ts, client/src/utils/localStorage.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/results/components/DirectResults.tsx, yarn.lock
* Save AllGames `searchTerm`, `tag` and `currentView` to localStorage
* Reset values on logout
* Add `Input` component
=> Save AllGames searchTerm, tag and view to localStorage

server/package.json, yarn.lock
update eventassigner-random to latest version
=> updated eventassigner-random

client/src/locales/en.json, client/src/locales/fi.json
Update registration code info text
=> Update registration code info text

client/src/components/Button.tsx
Add missing aria-label prop to Button
=> Add missing aria-label prop to Button

client/src/views/results/components/DirectResults.tsx
=> Show all results

client/src/components/TestValuePicker.tsx, client/src/config.ts, client/src/test/test-components/SignupStrategySelector.tsx, client/src/test/test-components/testComponentUtils.ts
Add more test times and hide strategy test value
=> Add more test times and hide strategy test value

client/src/views/all-games/AllGamesView.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/results/components/DirectResults.tsx
=> Make search case-insensitive

client/src/views/helper/components/PrivateSignupMessages.tsx, server/src/features/user/userController.test.ts, server/src/features/user/userController.ts, server/src/features/user/userService.ts
Don't allow helper to change helper or admin password
=> Don't allow helper to change helper or admin password

client/src/app/App.tsx, client/src/components/EventTypeSelection.tsx, client/src/components/LanguageSelector.tsx, client/src/globalStyle.ts, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameListTitle.tsx
=> Set global mobile margin

client/src/views/my-games/components/EnteredGameRow.tsx
=> Improve entered games layout

client/src/views/all-games/AllGamesView.tsx
Fix tag selection position in mobile
=> Fix tag selection position in mobile

client/src/views/admin/AdminView.tsx
=> Change test button location

client/src/index.tsx, client/src/utils/store.ts, server/package.json, server/src/api/apiRoutes.ts, server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/features/sentry-tunnel/sentryTunnelService.ts, server/src/utils/server.ts, shared/constants/apiEndpoints.ts
=> Add sentry tunnel endpoint

client/src/utils/store.ts, server/src/test/test-data-generation/generators/generateTestData.ts, server/src/test/test-data-generation/runGenerators.ts
Don't send large payload to sentry
=> Don't send large payload to sentry

client/src/index.tsx, server/src/utils/server.ts, shared/config/sharedConfig.ts, shared/constants/apiEndpoints.ts
Disable sentry perf monitoring
=> Disable sentry perf monitoring

client/src/utils/api.ts, client/src/utils/store.ts
=> Fix api error error

client/src/app/App.tsx, client/src/index.tsx, client/src/utils/localStorage.ts
Do page reload if trying to download old bundle
=> Do page reload if trying to download old bundle

client/src/utils/store.ts
Make sentry state transforms optional
=> Make sentry state transforms optional

client/src/views/all-games/components/GameEntry.tsx
=> Tag content is depended on its height

client/src/components/EventTypeSelection.tsx, client/src/views/all-games/AllGamesView.tsx
=> Fix tag selection positioning

client/src/utils/api.ts
=> Check for return code 0

server/src/features/player-assignment/utils/getAssignmentBonus.ts, server/src/features/player-assignment/utils/getList.test.ts
Don't include wrong program types in first time bonus calculation
=> Don't include wrong program types in first time bonus calculation

server/src/features/player-assignment/utils/getDynamicStartingTime.ts, server/src/utils/cron.ts, server/src/utils/server.ts
Use start of minute on dynamic time and close cron properly
=> Use start of minute on dynamic time and close cron properly

client/src/locales/en.json
=> Fix english title

client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/utils/getUpcomingGames.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx
=> Selected game is now blue bordered and has infobox on them

client/src/app/App.tsx
Show program type selection to admin if app closed
=> Show program type selection to admin if app closed

server/src/utils/server.ts
Set invalid request logging to warn
=> Set invalid request logging to warn

server/src/config.ts, server/src/features/player-assignment/runAssignment.test.ts
=> Improve assignment test

client/src/locales/en.json, client/src/locales/fi.json
Update term game master to game organizer
=> Update term game master to game organizer

client/src/views/admin/AdminView.tsx, server/src/utils/server.ts, shared/config/sharedConfig.ts
Add config enableSentryTesting and use it ot hide sentry tests
=> Add config enableSentryTesting and use it ot hide sentry tests

client/src/markdown/PrivacyPolicyEn.md, client/src/markdown/PrivacyPolicyFi.md, server/src/features/player-assignment/runAssignment.test.ts
=> Update privacy policy

client/src/locales/en.json, client/src/locales/fi.json, client/src/markdown/AboutKonstiEn.md, client/src/markdown/AboutKonstiFi.md, client/src/markdown/KonstiFaqEn.md, client/src/markdown/KonstiFaqFi.md, client/src/views/about/AboutView.tsx, server/src/features/player-assignment/runAssignment.test.ts
=> Update about Konsti page

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx, shared/config/sharedConfig.ts
Add game to directSignupAlwaysOpen and update info text style
=> Add game to directSignupAlwaysOpen and update info text style

client/src/markdown/AboutKonstiEn.md, client/src/markdown/AboutKonstiFi.md, client/src/markdown/KonstiFaqEn.md, client/src/markdown/KonstiFaqFi.md
Add English FAQ and About Konsti
=> Add English FAQ and About Konsti

client/src/locales/en.json
=> Fix overflowing button text

client/src/views/all-games/AllGamesView.tsx
Improve revolving door instructions styling
=> Improve revolving door instructions styling

client/src/components/FirstLogin.tsx
Add mobile margin to first time login notification
=> Add mobile margin to first time login notification

client/src/app/App.tsx, client/src/components/EventTypeSelection.tsx, client/src/components/FirstLogin.tsx, client/src/views/all-games/components/GameListTitle.tsx
Add mobile margin to tablet resolution
=> Add mobile margin to tablet resolution

client/jest.config.ts, client/src/typings/declarations/global.d.ts, package.json, server/jest.config.ts, server/src/features/player-assignment/runAssignment.test.ts, server/src/typings/declarations/global.d.ts, server/tsconfig.json, yarn.lock
Improve assignment test by checking group members
=> Improve assignment test by checking group members

client/src/locales/en.json, client/src/locales/fi.json, client/src/test/test-components/testComponentUtils.ts, client/src/views/group/GroupView.tsx, client/src/views/group/components/NotInGroupActions.tsx, shared/typings/models/game.ts
=> Text improvements

client/src/test/test-components/testComponentUtils.ts, server/src/test/test-data-generation/generators/createSignedGames.ts
=> Add more test times

client/src/utils/store.ts
Don't log admin/submitGetSettingsAsync action to sentry
=> Don't log admin/submitGetSettingsAsync action to sentry

server/src/features/player-assignment/runAssignment.ts
Don't save results if not results
=> Don't save results if not results

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/AllGamesView.tsx
Don't show hidden games on running revolving door games
=> Don't show hidden games on running revolving door games

client/src/markdown/PrivacyPolicyFi.md
=> Update FI registry policy

client/src/views/all-games/components/GameInfo.tsx
Fix number of players if min is zero
=> Fix number of players if min is zero

client/src/views/all-games/AllGamesView.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/results/components/DirectResults.tsx
Strip multiple whitespaces from searched values
=> Strip multiple whitespaces from searched values

server/src/features/player-assignment/runAssignment.test.ts
=> Add first time bonus test

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/group/groupThunks.ts, server/src/features/user/group/groupService.ts, shared/typings/api/groups.ts
Group backend validation for existing signed games
=> Group backend validation for existing signed games

client/src/locales/en.json, client/src/views/all-games/components/EnterGameForm.tsx, server/src/features/player-assignment/runAssignment.test.ts, server/src/features/player-assignment/utils/getAssignmentBonus.ts
Don't leave or break group when signing to directSignupAlwaysOpen game
=> Don't leave or break group when signing to directSignupAlwaysOpen game

client/src/components/PopularityInfo.tsx
Fix popularity message translations
=> Fix popularity message translations

server/src/utils/kompassiGameMapper.ts, shared/typings/models/kompassiGame.ts
=> Add tag youtube

client/src/views/all-games/components/GameEntry.tsx
Show game full if more players than max
=> Show game full if more players than max

server/package.json, server/src/test/scripts/updateSignups.ts
=> Add updateSignups script

README.md, client/src/components/TextArea.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AdminActionCard.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/ExpandedGameDescription.tsx, client/src/views/all-games/components/FeedbackForm.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameDetailsView.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameInfo.tsx, package.json
On the all games list page, the user can view game details without navigating away from the game list. To avoid code duplication, the game page now uses the same game card as the game list to show information.
=> Show game details in game list

.github/workflows/nodejs.yml, Dockerfile, package.json
=> Update to Node 18 LTS

client/package.json, client/src/components/TestValuePicker.tsx, client/src/typings/declarations/i18next.d.ts, client/src/typings/declarations/react-i18next.d.ts, client/src/utils/api.ts, client/src/utils/validate.ts, yarn.lock
Fix i18next typechecking. Before typed on `react-i18next`, now on `i18next`.
https://www.i18next.com/overview/typescript
=> Fix i18next typechecking

.github/workflows/nodejs.yml
Update setup-node Github action
=> Update setup-node Github action

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx, server/src/features/game/gameSchema.ts, server/src/utils/kompassiGameMapper.ts, shared/config/sharedConfig.ts, shared/typings/models/game.ts, shared/typings/models/kompassiGame.ts
* Ladataan työpajojen tiedot Kompassista
* Näytetään työpajat Konstin ohjelmalistauksessa omana ohjelmatyyppinään
* Muutettu `Pelaajia` teksti `Osallistujia`, kun kyseessä on työpaja
=> Add workshops

.github/workflows/nodejs.yml
=> Rename master to main

client/src/components/FavoriteButton.tsx, client/src/theme.ts, client/src/views/my-games/components/GamesByStartTimes.tsx
Remove drop shadow from favorite button (because it was too much). Fine-tune said button a little.
=> Tune favorite button.

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/GameEntry.tsx, server/src/features/game/gameRepository.ts, server/src/features/game/gameSchema.ts, server/src/test/mock-data/mockKompassiGame.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/utils/kompassiGameMapper.ts, shared/tests/testGame.ts, shared/typings/models/game.ts, shared/typings/models/kompassiGame.ts
* Lisätään `Game` tyyppiin `entryFee` eli osallistumismaksu. Työpajoilla voi olla osallistumismaksu.
* Näytetään osallistumismaksu ohjelmalistauksessa
* Näytetään lisähuomautus, jos ollaan ilmoittautumassa ohjelmanumeroon, jolla on osallistumismaksu
* `yarn run populate-db:dummy` generoi työpajaohjelmia ja lisää niille kaikille osallistumismaksun
=> Add program entry fee

server/src/features/player-assignment/group/groupAssignPlayers.ts, server/src/features/player-assignment/munkres/munkresAssignPlayers.ts, server/src/features/player-assignment/padg/padgAssignPlayers.ts, server/src/features/player-assignment/random/randomAssignPlayers.ts, server/src/features/player-assignment/runAssignmentGroup.test.ts, server/src/features/player-assignment/runAssignmentGroupPadg.test.ts, server/src/features/player-assignment/runAssignmentPadg.test.ts, server/src/features/player-assignment/runAssignmentRandom.test.ts, server/src/features/player-assignment/runAssignmentRandomPadg.test.ts, server/src/typings/result.typings.ts
Add `AssignmentResultStatus` enum
=> Add AssignmentResultStatus enum

server/src/middleware/wwwRedirect.ts
Second attempt to fix `Can't set headers after they are sent.`
=> Fix cannot set headers bug

.github/workflows/nodejs.yml
Increase CI timeout 20 -> 30min
=> Increase CI timeout 20 -> 30min

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx
Use second i18next key instead of variable
=> Use second i18next key instead of variable

client/src/components/EventTypeSelection.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/components/UserNavigation.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/markdown/AboutKonstiEn.md, client/src/markdown/AboutKonstiFi.md, client/src/utils/getAttendeeType.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/GameEntry.tsx
* Improve program list translations: use program type aware translations
=> Improve program list translations

client/package.json, client/tsconfig.json, client/webpack.config.ts, package.json, yarn.lock
=> Update webpack-cli major v5

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/results/components/DirectResults.tsx
=> Translate results view

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/my-games/myGamesThunks.ts
Add missing program type aware translation
=> Add missing program type aware translation

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/my-games/myGamesThunks.ts
Improve program type aware translations
=> Improve program type aware translations

client/src/app/AppRoutes.tsx, client/src/components/Tabs.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/utils/icons.ts, client/src/views/about/AboutView.tsx, client/src/views/about/FaqView.tsx, yarn.lock
* Add tab navigation UI element
* Use it in the about section
=> Add tab navigation UI element

client/webpack.config.ts, server/package.json, yarn.lock
* Roll back mongoose version
* Staging is experiencing `cursor id not found` errors
=> Roll back mongoose version

server/src/config.ts
Disable auto assign on staging
=> Disable auto assign on staging

server/src/config.ts
Disable cronjobs from staging to debug DB issue
=> Disable cronjobs from staging

server/src/config.ts
Enable automatic game updates on staging
=> Enable automatic game updates on staging

client/.eslintrc.js, client/src/app/App.tsx, client/src/components/Dropdown.tsx, client/src/components/EventTypeSelection.tsx, client/src/components/RadioButton.tsx, client/src/components/UncontrolledInput.tsx, client/src/config.ts, client/src/locales/en.json, client/src/locales/fi.json, client/src/theme.ts, client/src/utils/localStorage.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameListTitle.tsx, client/src/views/all-games/components/RevolvingDoorGamesInfo.tsx, client/src/views/all-games/components/SearchAndFilterCard.tsx, client/src/views/group/GroupView.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/my-games/myGamesSlice.ts, client/src/views/results/components/ResultsList.tsx, client/src/views/results/components/SearchAndFilterResultsCard.tsx
- Laitetaan inputit ohjelman hakuun ja filtteröintiin uuteen käyttöliittymäkorttiin
- mygames-sivu näyttää nyt kaikentyyppisen ohjelman. (Sivun enempi tyylittely lienee erillinen taski.)
Tässä branchissa poistuu äsken lisätty toiminnallisuus, jossa voi poistaa Konstista mahdollisuuden valita näytettävän ohjelman ajankohta (koska logiikan vasarointi tähän mukaan tuntui hyötyyn nähden työläältä etenkin kälielementtien tyylittelyn kannalta). Jos tämä toiminnallisuus on tärkeä, olisiko parempi laittaa konffiin mahdollisuus valita aikavalinnan default-arvo (ts. kaikki vs. tulevat)?
=> Style search and filter options 

server/src/utils/cron.ts, server/src/utils/logger.ts
Pass errors correctly to Sentry
=> Pass errors correctly to Sentry

server/src/features/game-popularity/updateGamePopularity.test.ts, server/src/features/game-popularity/utils/updateWithAssign.ts, server/src/features/game-popularity/utils/updateWithSignups.ts, server/src/features/game/gameRepository.ts
Improve popularity update performance
=> Improve popularity update performance

server/src/config.ts
Disable popularity autoupdate on staging
=> Disable popularity autoupdate on staging

server/src/config.ts, server/src/features/game-popularity/updateGamePopularity.ts, server/src/features/game/gameRepository.ts, server/src/features/game/gamesService.ts, server/src/features/game/utils/getGamesFromKompassi.ts, server/src/features/player-assignment/utils/removeInvalidGamesFromUsers.ts, server/src/features/player-assignment/utils/removeMovedGamesFromUsers.ts, server/src/features/settings/utils/removeHiddenGamesFromUsers.ts, server/src/features/signup/signupRepository.ts, server/src/features/user/userRepository.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/utils/cron.ts
* Use bulk or many operations when updating games
* Remove `autoUpdateGamePopularityEnabled` since `updateGamePopularityEnabled` does the same
=> Use bulk or many operations when updating games

server/src/features/game/utils/getGamesFromKompassi.ts, server/src/features/player-assignment/group/utils/getHappiness.ts, server/src/features/player-assignment/group/utils/runGroupAssignment.ts, server/src/features/player-assignment/munkres/utils/buildSignupResults.ts, server/src/features/player-assignment/padg/utils/runPadgAssignment.ts, server/src/features/player-assignment/random/utils/runRandomAssignment.ts, server/src/features/player-assignment/utils/formatResults.ts, server/src/features/player-assignment/utils/getGroups.ts, server/src/features/player-assignment/utils/getList.ts, server/src/features/player-assignment/utils/removeOverlapSignups.ts, server/src/features/player-assignment/utils/verifyUserSignups.ts, server/src/features/sentry-tunnel/sentryTunnelService.ts, server/src/features/settings/settingsRepository.ts, server/src/features/signup/signupRepository.ts, server/src/features/signup/signupService.ts, server/src/features/user/favorite-game/favoriteGameRepository.ts, server/src/features/user/signed-game/signedGameRepository.ts, server/src/test/scripts/testAssignPlayers.ts, server/src/test/scripts/updateSignups.ts, server/src/utils/cron.ts, server/src/utils/generateSerials.ts
Create new errors when logging own errors
Before:
```ts
logger.error("Invalid response format, should be array");
```
After:
```ts
logger.error("%s", new Error("Invalid response format, should be array"));
```
=> Create new errors when logging own errors

server/src/features/feedback/feedbackController.ts, server/src/features/results/resultsController.ts, server/src/features/settings/settingsController.ts, server/src/features/signup/signupController.ts, server/src/features/user/favorite-game/favoriteGameController.ts, server/src/features/user/group/groupController.ts, server/src/features/user/login/loginController.ts, server/src/features/user/signed-game/signedGameController.ts, server/src/features/user/userController.ts, server/src/test/test-settings/testSettingsController.ts
Replace zod `parse` with `safeParse`
* https://github.com/colinhacks/zod#parse
* https://github.com/colinhacks/zod#safeparse
=> Replace zod parse with safeParse

server/src/features/game/gameController.test.ts, server/src/features/game/utils/getGamesFromKompassi.ts, server/src/test/setupTests.ts, shared/typings/models/kompassiGame.ts
Allow saving program items with invalid values, drop and log invalid values
=> Allow saving program items with invalid values, drop invalid values

server/src/config.ts
Enable game auto update on staging
=> Enable game auto update on staging

server/src/config.ts
Disable game autoupdate on staging
=> Disable game autoupdate on staging

server/src/api/apiRoutes.ts, server/src/config.ts, server/src/features/game/gameController.ts, server/src/features/results/resultsController.ts, server/src/utils/authHeader.ts, server/src/utils/cron.ts, shared/constants/apiEndpoints.ts
=> Add cron endpoints

server/src/config.ts
Reduce PADG rounds for staging
=> Reduce PADG rounds for staging

server/src/features/game/gameController.ts, server/src/features/results/resultsController.ts
Cron endpoints don't wait for response
=> Cron endpoints don't wait for response

client/src/views/all-games/components/EventLog.tsx
Show relative time for same day
=> Show relative time for same day

client/playwright/tests/add-favorite.spec.ts, client/playwright/tests/login.spec.ts, client/src/app/AppRoutes.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/components/Navigation.tsx, client/src/components/RaisedCard.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/icons.ts, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/SearchAndFilterCard.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/my-games/MyGamesView.tsx, client/src/views/profile/ProfileView.tsx, client/src/views/results/components/SearchAndFilterResultsCard.tsx
Lisätään uusi näkymä profiilin ja ryhmän tiedoille. Tyylitellään vähän näkymän komponentteja.
=> Add new profile page

client/playwright/tests/add-favorite.spec.ts, client/src/components/RaisedCard.tsx
Fix add-favorite playwright test
=> Fix add-favorite playwright test

server/src/features/player-assignment/utils/saveUserSignupResults.ts, server/src/features/user/event-log/eventLogRepository.test.ts, server/src/features/user/event-log/eventLogRepository.ts
Only remove new assignment events
=> Only remove new assignment events

server/src/test/scripts/testAssignPlayers.ts, shared/config/sharedConfig.ts
=> Update convention start time

client/src/components/LoggedInUserNavigation.tsx, client/src/components/Navigation.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/icons.ts, client/src/views/all-games/components/EventLog.tsx
Show badge with new event count
=> Show badge with new event count

client/src/app/App.tsx, client/src/components/NotificationBar.tsx, client/src/views/login/loginSlice.ts, client/src/views/login/loginThunks.ts, client/src/views/my-games/myGamesThunks.ts
Update eventLogItems with other user data
=> Update eventLogItems with other user data

client/src/views/all-games/components/EventLog.tsx, server/src/features/game/gameRepository.ts
Use RaisedCard for no notifications message
=> Use RaisedCard for no notifications message

client/src/views/all-games/components/SearchAndFilterCard.tsx
Show revolving door games only for RPGs
=> Show revolving door games only for RPGs

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/helper/components/PasswordManagement.tsx, server/src/features/player-assignment/utils/getList.test.ts, server/src/features/user/userService.ts, server/src/test/test-data-generation/generators/createEventLogItems.ts, shared/typings/api/users.ts, shared/typings/models/user.ts
Add createdAt info to password reset
=> Add createdAt info to password reset

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/api.ts, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/GameEntry.tsx, server/src/features/game/gameSchema.ts, server/src/test/mock-data/mockKompassiGame.ts, server/src/test/test-data-generation/generators/createGames.ts, shared/tests/testGame.ts, shared/typings/models/game.ts, shared/typings/models/kompassiGame.ts
Update Kompassi export values signuplist and workshop fee
=> Update Kompassi export values signuplist and workshop fee

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/getAttendeeType.ts, client/src/views/all-games/components/DirectSignupForm.tsx, server/src/features/game/utils/getGamesFromKompassi.ts, server/src/utils/kompassiGameMapper.ts, shared/config/sharedConfig.ts, shared/typings/models/game.ts, shared/typings/models/kompassiGame.ts
Add games based on signup type
=> Add games based on signup type

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx
Show signup open time if not logged
=> Show signup open time if not logged

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/registration/RegistrationView.tsx
Change create account to log in
=> Change create account to log in

client/src/utils/timeFormatter.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/GameListTitle.tsx
If lottery signup starts too early it starts last evening
=> If lottery signup starts too early it starts last evening

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/admin/adminThunks.ts, client/src/views/admin/components/SignupQuestionList.tsx, client/src/views/all-games/components/AdminActionCard.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, client/src/views/results/components/ResultsList.tsx, server/src/features/game/gameController.test.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsSchema.ts, server/src/features/user/signup-message/signupMessageController.test.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/generators/createSignups.ts, shared/typings/models/settings.ts
Add select option for signup question
=> Add select option for signup question

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/admin/adminThunks.ts, client/src/views/admin/components/SignupQuestionList.tsx, client/src/views/all-games/components/AdminActionCard.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/helper/components/PrivateSignupMessages.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, client/src/views/results/components/ResultsList.tsx, server/src/features/game/gameController.test.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsSchema.ts, server/src/features/user/signup-message/signupMessageController.test.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/generators/createSignups.ts, shared/typings/models/settings.ts
Add language support to signup questions
=> Add language support to signup questions

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx
=> Add no signup required state

client/src/locales/en.json, client/src/locales/fi.json
Update material fee confirmation text
=> Update material fee confirmation text

client/src/components/NotificationBar.tsx, client/src/locales/en.json, client/src/locales/fi.json
Add show all link to notification
=> Add show all link to notification

client/src/views/all-games/components/EnterGameForm.tsx
Add max width to signup select
=> Add max width to signup select

client/src/index.html
=> Prevent index.html caching

server/src/test/test-data-generation/generators/createUsers.ts, server/src/utils/initializeDatabase.ts
=> Improve initialize db script

shared/config/sharedConfig.ts, shared/utils/getDirectSignupStartTime.ts
Add tournament signup times
Perjantain turnaukset: pe klo 15
Lauantain turnaukset: pe klo 18
Sunnuntain turnaukset: la klo 18
=> Add tournament signup times

client/src/app/App.tsx, client/src/index.tsx, client/src/utils/lazyWithRetry.ts, client/src/utils/localStorage.ts, client/webpack.config.ts
Improved chunk load failed handling
=> Improved chunk load failed handling

client/src/components/Checkbox.tsx, client/src/views/all-games/components/AdminActionCard.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/registration/components/RegistrationForm.tsx
* Make checkbox label clickable
* Add new `Checkbox` component
=> Make checkbox label clickable

server/src/features/game/gameRepository.ts, server/src/features/player-assignment/runAssignment.test.ts, server/src/features/signup/signupController.test.ts, server/src/features/signup/signupRepository.ts
Fix signup race condition when signing to last spot
=> Fix signup race condition when signing to last spot

server/src/features/game/gameRepository.test.ts, server/src/features/game/gameUtils.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/utils/removeHiddenGamesFromUsers.ts, server/src/features/signup/signupRepository.ts
* Remove signup document when program item is removed
* Reset signups when program item is hidden but don't remove signup document
=> Remove signup document when program item is removed

client/src/views/all-games/components/EnterGameForm.tsx, server/src/features/player-assignment/runAssignment.test.ts, server/src/features/player-assignment/utils/saveUserSignupResults.ts, server/src/features/signup/signupController.test.ts, server/src/features/signup/signupRepository.ts, server/src/test/mock-data/mockUser.ts, server/src/test/test-data-generation/generators/createSignups.ts, shared/constants/signups.ts, shared/typings/api/myGames.ts
Save correct priority value for signup
=> Save correct priority value for signup

server/src/config.ts, server/src/features/game/utils/getGamesFromKompassi.ts, server/src/features/signup/signupController.ts, server/src/features/user/event-log/eventLogController.ts, server/src/features/user/favorite-game/favoriteGameController.test.ts, server/src/features/user/login/loginController.test.ts, server/src/features/user/signed-game/signedGameController.test.ts, server/src/features/user/userController.test.ts, server/src/test/setupTests.ts, server/src/test/test-data-generation/testDataController.test.ts, server/src/test/test-settings/testSettingsController.test.ts
=> Refactor some server tests

client/src/components/LazyLoadingFallback.tsx, client/src/index.tsx, client/src/utils/lazyWithRetry.ts
Add lazy loading fallback component
=> Add lazy loading fallback component

client/src/config.ts, client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx, shared/config/sharedConfig.ts
Add noKonstiSignup program items
=> Add noKonstiSignup program items

client/src/markdown/KonstiFaqEn.md, client/src/markdown/KonstiFaqFi.md, client/src/markdown/KonstiInstructionsEn.md, client/src/markdown/KonstiInstructionsFi.md
=> Update hall 3 to hall 5

server/src/config.ts, server/src/test/test-data-generation/runGenerators.ts, server/src/utils/cleanupDatabse.ts, server/src/utils/initializeDatabase.ts
=> Add cleanupDatabase

server/src/features/settings/settingsRepository.ts, server/src/utils/cron.test.ts
Improve duplicate cron check code
=> Improve duplicate cron check code

.eslintrc.js, server/src/features/player-assignment/group/groupAssignPlayers.ts, server/src/features/player-assignment/munkres/munkresAssignPlayers.ts, server/src/features/player-assignment/padg/padgAssignPlayers.ts, server/src/features/player-assignment/random/randomAssignPlayers.ts, server/src/features/player-assignment/runAssignmentGroupPadg.test.ts, server/src/features/player-assignment/runAssignmentRandomPadg.test.ts, server/src/features/player-assignment/utils/runAssignmentStrategy.ts, server/src/typings/result.typings.ts
If other assignment fails, return other
=> If other assignment fails, return other

server/package.json, server/src/config.ts, server/src/features/signup/signupRepository.ts
* Filter out signups with failed populate
* Add `--transpile-only` to start script
=> Filter out signups with failed populate

docker/docker-compose.yml, server/src/index.ts, server/src/utils/server.ts
Improve server start error handling
=> Improve server start error handling

shared/config/sharedConfig.ts, shared/utils/signupTimes.ts
Add signup window for experience point and other program
=> Add signup window for experience point and other program

server/src/config.ts, server/src/index.ts
Start cronjobs only if env var set
=> Start cronjobs only if env var set

server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/utils/sentry.ts
Don't wait for Sentry response
=> Don't wait for Sentry response

server/src/config.ts, server/src/index.ts, server/src/utils/cron.ts
=> Add more cronjob logging

server/src/index.ts
=> Add more logging

docker/docker-compose.yml, package.json, server/src/test/setupTests.ts
=> Update MongoDB to 6.0.8

server/src/features/signup/signupRepository.ts
Improve logging for signup cancel
=> Improve logging for signup cancel

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameInfo.tsx, client/src/views/all-games/components/RevolvingDoorGamesInfo.tsx, client/src/views/all-games/components/SearchAndFilterCard.tsx, server/src/utils/kompassiGameMapper.ts
Show revolving door for all program types and list revolving door workshops
=> Show revolving door for all program types and list revolving door workshops

server/src/features/feedback/feedbackController.ts, server/src/features/game/gameSchema.ts, server/src/features/results/resultsController.ts, server/src/features/settings/settingsController.ts, server/src/features/signup/signupController.ts, server/src/features/user/event-log/eventLogController.ts, server/src/features/user/favorite-game/favoriteGameController.ts, server/src/features/user/group/groupController.ts, server/src/features/user/login/loginController.ts, server/src/features/user/signed-game/signedGameController.ts, server/src/features/user/userController.ts, server/src/test/test-settings/testSettingsController.ts
Rename program item schema field
=> Rename program item schema field

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/AllGamesList.tsx
Use program type aware text for no program text
=> Use program type aware text for no program text

server/src/features/player-assignment/utils/saveUserSignupResults.test.ts, server/src/features/player-assignment/utils/saveUserSignupResults.ts, server/src/features/signup/signupRepository.test.ts, server/src/features/signup/signupRepository.ts
Don't add event if result is dropped
=> Don't add event if result is dropped

server/src/utils/server.ts
Don't send index html if cron only
=> Don't send index html if cron only

client/src/views/all-games/components/SearchAndFilterCard.tsx
=> Update tag filters

server/src/features/settings/settingsRepository.ts
Add debug logging for cronjob limiters
=> Add debug logging for cronjob limiters

server/src/features/settings/settingsRepository.ts
=> Add more cronjob debug loggin

server/src/index.ts, server/src/utils/cron.ts
Start cronjobs after server start
=> Start cronjobs after server start

client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, server/src/features/signup/signupRepository.test.ts, server/src/features/signup/signupRepository.ts
=> Add loading states

server/src/features/settings/settingsRepository.ts
=> Remove debug logging

client/src/views/all-games/components/CancelSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/SignupForm.tsx
Add loading states to cancel buttons
=> Add loading states to cancel buttons

client/src/views/all-games/components/GameEntry.tsx
Adjust program item title click area
=> Adjust program item title click area

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/isRevolvingDoorWorkshop.ts, client/src/views/all-games/components/GameEntry.tsx, client/src/views/results/components/ResultsList.tsx
Filter out revolving door workshops and no signups from results view
=> Filter out revolving door workshops and no signups from results view

client/src/test/test-components/testComponentUtils.ts, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/helper/HelperView.tsx, server/src/test/scripts/testAssignPlayers.ts
=> Small fixes from demo prep

server/src/utils/kompassiGameMapper.ts, shared/typings/models/kompassiGame.ts
Add miniature demo program category
=> Add miniature demo program category

server/src/utils/kompassiGameMapper.ts
Move miniature demo to other program category
=> Move miniature demo to other program category

server/src/features/game/gameController.test.ts, server/src/features/game/utils/addSignupQuestions.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsRepository.test.ts, server/src/features/settings/settingsRepository.ts, server/src/features/user/signup-message/signupMessageController.test.ts, server/src/test/scripts/loadKompassiDataToDb.ts, server/src/utils/initializeDatabase.ts, shared/config/sharedConfig.ts
Add signup questions to config
=> Add signup questions to config

server/src/config.ts, server/src/test/scripts/testAssignPlayers.ts
Don't verify signups after manual assignment
=> Don't verify signups after manual assignment

client/src/utils/getShortDescriptionFromDescription.ts, client/src/views/all-games/components/GameDetailsView.tsx
Build short description from long description
=> Build short description from long description

client/src/views/all-games/allGamesUtils.ts, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameEntry.tsx, server/src/features/game/gameUtils.ts, shared/utils/tooEearlyForAlgorithmSignup.ts
Move early algorithm signup check to backend
=> Move early algorithm signup check to backend

client/src/test/test-components/TestTime.tsx
Load data when test time changes
=> Load data when test time changes

server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsRepository.ts, server/src/features/settings/settingsSchema.ts, server/src/index.ts, server/src/utils/cron.test.ts, server/src/utils/cron.ts, shared/typings/models/settings.ts
Check if latest server instance before running cronjobs
=> Check if latest server instance before running cronjobs

server/src/utils/cron.ts
Don't use test time for server start time
=> Don't use test time for server start time

server/src/config.ts
Update Kompassi program every 7 minutes
=> Update Kompassi program every 7 minutes

.eslintrc.js, server/src/config.ts, server/src/features/game-popularity/updateGamePopularity.test.ts, server/src/features/game-popularity/updateGamePopularity.ts, server/src/features/game-popularity/utils/updateWithAssign.ts, server/src/features/game/gameRepository.ts, server/src/features/player-assignment/utils/getTimeNow.ts, server/src/features/signup/signupController.test.ts, server/src/features/signup/signupService.ts, server/src/test/scripts/loadKompassiDataToDb.ts, server/src/test/scripts/testUpdateGamePopularity.ts, server/src/test/test-data-generation/generators/createSignedGames.ts, server/src/test/test-data-generation/parseCliOptions.ts, server/src/test/test-data-generation/runGenerators.ts
Update popularity only for upcoming program items
=> Update popularity only for upcoming program items

server/src/features/player-assignment/utils/removeOverlapSignups.ts, server/src/index.ts
Add missing dayjs initialization
=> Add missing dayjs initialization

server/src/utils/cron.ts
=> Add more logging to cronjobs

client/src/utils/loadData.ts, server/src/features/game/gameUtils.ts, server/src/test/test-data-generation/generators/createGames.ts, server/src/test/test-data-generation/generators/createSignedGames.ts, server/src/utils/cron.ts, shared/config/sharedConfig.ts
Fix bug with program details page showing wrong signup mode
=> Fix bug with program details page showing wrong signup mode

server/src/features/signup/signupRepository.ts, shared/config/sharedConfig.ts
Add indie room to no Konsti signup list
=> Add indie room to no Konsti signup list

shared/config/sharedConfig.ts
Add more program items to no Konsti signup list
=> Add more program items to no Konsti signup list

server/src/utils/kompassiGameMapper.ts, shared/config/sharedConfig.ts
Add manual revolving door program items
=> Add manual revolving door program items

client/src/views/all-games/components/SignupForm.tsx
Fix priority dropdown selection not updating
=> Fix priority dropdown selection not updating

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/my-games/components/MySignupsList.tsx
Add group creator text to my program page
=> Add group creator text to my program page

client/src/views/my-games/components/MySignupsList.tsx
Add group creator text to my program page, second attempt
=> Add group creator text to my program page, second attempt

server/src/config.ts
Set program update cron to fire at fixed intervals
=> Set program update cron to fire at fixed intervals

server/src/features/player-assignment/padg/utils/assignPadg.ts
Filter out invalid assignment responses
=> Filter out invalid assignment responses

server/src/features/user/group/groupService.ts
Allow creating/joining group if non-RPG signups
=> Allow creating/joining group if non-RPG signups

shared/config/sharedConfig.ts
Add impro program number to Konsti
=> Add impro program number to Konsti

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/my-games/myGamesThunks.ts, server/src/features/signup/signupService.ts, shared/typings/api/myGames.ts
Backend validation for no Konsti signup
=> Backend validation for no Konsti signup

client/src/utils/loadData.ts
Don't download program if app closed
=> Don't download program if app closed

server/src/features/statistics/fixer-helpers/formatFeedbacks.ts, server/src/features/statistics/statsUtil.ts
=> Add feedback format function

client/package.json, client/src/components/Button.tsx, client/src/components/FavoriteButton.tsx, client/src/components/LoggedInUserNavigation.tsx, client/src/components/RaisedCard.tsx, client/src/components/UserNavigation.tsx, client/src/index.tsx, client/src/views/admin/AdminView.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameListTitle.tsx, yarn.lock
Fix styled-components 6 regressions
* Mark props as transient props (`$`)
* Enable vendor prefixes
=> Fix styled-components 6 regressions

.yarnrc.yml
=> Fix missing peer dep warning

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx
Add Kompassi login to help page
=> Add Kompassi login to help page

server/src/utils/sentry.ts, server/src/utils/server.ts
Fix CSP `connect-src` for Docker compose
=> Fix CSP connect-src for Docker compose

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx
Remove registration code from Hitpoint guide
=> Remove registration code from Hitpoint guide

client/config/staging.env, client/src/index.tsx
=> Rename test env to dev

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/RevolvingDoorGamesInfo.tsx
=> Improve UI texts

server/src/middleware/cors.ts
=> Improve CORS middleware

.github/workflows/build.yml, client/playwright/playwright.config.ts, package.json
Fix flaky e2e test compose exit
=> Fix flaky e2e test compose exit

.github/workflows/sentry.yml
Fix uploading Sentry release on CI workflow
=> Fix uploading Sentry release on CI workflow

.github/workflows/sentry.yml, .github/workflows/test.yml
=> Refactor CI workflows

server/src/features/auth/kompassiLogin.ts, server/src/features/player-assignment/utils/getList.test.ts, server/src/features/user/userRepository.ts, server/src/features/user/userSchema.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/typings/user.typings.ts, shared/typings/models/user.ts
Rename `userId` to `kompassiId`
=> Rename userId to kompassiId

shared/test-typings/api/testSettings.ts, shared/typings/api/assignment.ts, shared/typings/api/favorite.ts, shared/typings/api/feedback.ts, shared/typings/api/games.ts, shared/typings/api/groups.ts, shared/typings/api/login.ts, shared/typings/api/myGames.ts, shared/typings/api/results.ts, shared/typings/api/settings.ts, shared/typings/api/users.ts
=> Improve ApiResult type

server/src/api/apiRoutes.ts, server/src/features/kompassiLogin/kompassiLoginController.ts, server/src/features/kompassiLogin/kompassiLoginService.ts, server/src/features/kompassiLogin/kompassiLoginUtils.ts, shared/typings/api/errors.ts, shared/typings/api/login.ts
* Move Kompassi login files around
* Disable Kompassi admin access, Konsti will handle admin accounts itself
=> Move Kompassi login files around, disable admin access

client/src/app/AppRoutes.tsx, client/src/components/KompassiLoginCallback.tsx, client/src/components/UserNavigation.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/views/login/LoginView.tsx, client/src/views/login/components/KompassiLogin.tsx, shared/typings/api/login.ts
* Add admin login path
* Show `Create Kompassi account` button
* Show button also when app is closed because Kompassi account can be created before event
* Redirect back to login if Kompassi login is canceled
=> Add admin login path

client/src/app/AppRoutes.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/services/loginServices.ts, client/src/typings/redux.typings.ts, client/src/views/login/components/KompassiLoginUsernameForm.tsx, client/src/views/login/loginSlice.ts, client/src/views/login/loginThunks.ts, server/src/api/apiRoutes.ts, server/src/features/kompassiLogin/kompassiLoginController.ts, server/src/features/kompassiLogin/kompassiLoginService.ts, server/src/features/player-assignment/utils/getList.test.ts, server/src/features/user/login/loginService.ts, server/src/features/user/session-restore/sessionRestoreService.ts, server/src/features/user/userRepository.ts, server/src/features/user/userSchema.ts, shared/constants/apiEndpoints.ts, shared/typings/api/login.ts, shared/typings/models/user.ts
Ask for Konsti username after first Kompassi login
=> Ask for Konsti username after first Kompassi login

client/src/services/loginServices.ts, server/src/api/apiRoutes.ts, server/src/features/kompassiLogin/kompassiLoginController.ts
Change Kompassi login method to POST to include origin
=> Change Kompassi login method to POST to include origin

shared/config/past-events/ropecon2023.ts, shared/config/sharedConfig.ts, shared/config/sharedConfigTypes.ts
Move Ropecon 2023 config to separate file
=> Move Ropecon 2023 config to separate file

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/GameInfo.tsx, client/src/views/all-games/components/SearchAndFilterCard.tsx, server/src/utils/kompassiGameMapperHitpoint.ts, shared/config/clientConfig.ts, shared/config/sharedConfig.ts, shared/typings/models/game.ts
Update Hitpoint program item tags and set 'no signup' program items
=> Update Hitpoint program item tags and set 'no signup' program items

shared/config/past-events/ropecon2023.ts, shared/config/sharedConfig.ts
Change Hitpoint start time to GMT+2
=> Change Hitpoint start time to GMT+2

client/src/utils/getUpcomingGames.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/my-games/MyGamesView.tsx
Bug: allow signup if not in group
=> Bug: allow signup if not in group

server/src/features/player-assignment/runAssignment.test.ts
Set correct mock active program type for test
=> Set correct mock active program type for test

client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/GameEntry.tsx, client/src/views/all-games/components/SignupForm.tsx, client/src/views/my-games/components/FavoritesByStartTimes.tsx
* Show multi-row warning
* Use selector functions
=> Show multi-row warning

client/src/views/all-games/components/SearchAndFilterCard.tsx
=> Enable language tag filters

client/src/markdown/AboutKonsti.mdx, client/src/markdown/KonstiInstructions.mdx
=> Update About page

client/src/app/AppRoutes.tsx, client/src/components/KompassiLoginCallback.tsx, client/src/components/KompassiLogoutCallback.tsx, client/src/locales/en.json, client/src/services/loginServices.ts, client/src/views/login/components/KompassiLogin.tsx, client/src/views/logout/LogoutView.tsx, server/src/api/apiRoutes.ts, server/src/features/kompassiLogin/kompassiLoginController.ts, server/src/features/kompassiLogin/kompassiLoginService.ts, server/src/features/kompassiLogin/kompassiLoginUtils.ts, server/src/features/serial/serialRepository.ts, shared/constants/apiEndpoints.ts
=> Add Kompassi logout

client/src/views/login/components/KompassiLoginUsernameForm.tsx, client/src/views/login/loginThunks.ts, server/src/features/kompassiLogin/kompassiLoginController.test.ts, server/src/features/kompassiLogin/kompassiLoginController.ts, server/src/features/kompassiLogin/kompassiLoginService.ts, shared/typings/api/login.ts
Check if username exists when selecting Konsti username
=> Check if username exists when selecting Konsti username

server/src/utils/kompassiGameMapperHitpoint.ts, shared/config/sharedConfig.ts
Add English language to program items
=> Add English language to program items

client/src/views/all-games/components/AllGamesList.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/all-games/components/GameDetails.tsx, client/src/views/all-games/components/GameEntry.tsx
Disable all signup buttons when signup in progress
Fixes #741
=> Bug: Disable all signup buttons when signup in progress

client/src/test/test-components/testComponentUtils.ts, client/src/views/my-games/utils/getMissedSignups.ts
Add safety period before showing 'no lottery game' message
=> Add safety period before showing 'no lottery game' message

client/src/locales/en.json, client/src/locales/fi.json, client/src/utils/icons.ts, client/src/views/all-games/components/EnterGameForm.tsx, client/src/views/my-games/components/EnteredGameRow.tsx, client/src/views/my-games/components/MyEnteredList.tsx, server/src/features/game/gameRepository.ts, server/src/features/player-assignment/utils/updateMovedGames.test.ts, server/src/features/player-assignment/utils/updateMovedGames.ts, server/src/features/user/group/groupService.ts, server/src/test/test-data-generation/generators/createUsers.ts
* Show correct time on MyProgram page  if program item startTime changes
* Show notification if time changed
* Use same function to seed group codes for test users
=> Show correct time if program item startTime changes

server/src/features/kompassiLogin/kompassiLoginService.ts, server/src/features/user/userRepository.ts, server/src/utils/cron.test.ts, server/src/utils/cron.ts
=> Improve logging

server/src/features/player-assignment/runAssignment.test.ts, server/vitest.config.ts, shared/config/sharedConfig.ts
Add larps to 'no Konsti signup' list
=> Add larps to 'no Konsti signup' list

client/src/views/all-games/components/GameEntry.tsx
Show number of players for 'no Konsti signup' program items
=> Show number of players for 'no Konsti signup' program items

server/src/features/player-assignment/runAssignment.test.ts, server/src/features/signup/signupRepository.ts
=> Replace moved direct signup with new lottery result

client/package.json, server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/features/sentry-tunnel/sentryTunnelService.ts, server/src/utils/sentry.ts, yarn.lock
Change Sentry tunnel payload to buffer type
=> Change Sentry tunnel payload to buffer type

server/src/features/kompassiLogin/KompassiLoginTypes.ts, server/src/features/kompassiLogin/kompassiLoginService.ts
Validate Kompassi tokens and profile with zod
=> Validate Kompassi tokens and profile with zod

server/src/features/serial/serialRepository.ts, server/src/utils/cleanupDatabse.ts
Add removeSerials() to cleanupDatabase()
=> Add removeSerials() to cleanupDatabase()

client/src/utils/localStorage.ts
Only read active program types from localStorage
=> Only read active program types from localStorage

client/src/components/LazyLoadingFallback.tsx, client/src/index.tsx, client/src/utils/lazyWithRetry.ts
Remove unnecessary LazyLoadingFallback and parse force refresh state with zod
=> Remove unnecessary LazyLoadingFallback and parse force refresh state with zod

client/src/components/FirstLogin.tsx, client/src/utils/lazyWithRetry.ts, client/src/utils/localStorage.ts
Parse remaining localStorage values with zod
=> Parse remaining localStorage values with zod

client/src/utils/localStorage.ts, client/src/utils/sessionStorage.ts, client/src/views/all-games/AllGamesView.tsx, client/src/views/all-games/components/SearchAndFilterCard.tsx, client/src/views/my-games/MyGamesView.tsx
Parse sessionStorage values with zod
=> Parse sessionStorage values with zod

server/tsconfig.json
Remove `files` config from `/server/tsconfig`
=> Remove files config from /server/tsconfig

package.json, yarn.lock
Remove old dependency resolution from package.json
=> Remove old dependency resolution from package.json

client/package.json, package.json, server/package.json
Fix typo in package.json type value
=> Fix typo in package.json type value

server/package.json, server/src/features/statistics/dataFixer.ts, server/src/features/statistics/similarUsernames.ts, yarn.lock
Add script to detect similar usernames
=> Add script to detect similar usernames

client/.eslintrc.js, package.json, yarn.lock
Remove unnecessary `eslint-plugin-testing-library`
=> Remove unnecessary eslint-plugin-testing-library

client/src/components/LoggedInUserNavigation.tsx, package.json, playwright/Dockerfile, playwright/docker-compose.yml, playwright/tests/login.spec.ts, playwright/tests/utils.ts
Import shared code in playwright tests
=> Import shared code in playwright tests

kubernetes/default.vars.yaml, kubernetes/development.vars.yaml, kubernetes/konsti/secret.in.yaml
=> Fix local kubernetes config

.github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, .github/workflows/test.yml
=> Fix emskaffolden CI install

.husky/pre-commit, README.md, client/src/markdown/AboutKonsti.mdx
* Update Konsti repository from `ropekonsti` to `con2`
* Update CI build badge to new workflow file
=> Update Konsti repository from ropekonsti to con2

kubernetes/default.vars.yaml, kubernetes/ingress.in.yaml, kubernetes/konsti/cron-deployment.in.yaml, kubernetes/konsti/konsti-deployment.in.yaml, kubernetes/production.vars.yaml, kubernetes/staging.vars.yaml, server/src/utils/server.ts, shared/config/serverConfig.ts
Add support for multiple ingress hostnames
=> Add support for multiple ingress hostnames

client/src/index.tsx, client/src/utils/localStorage.ts, shared/types/locale.ts
Reset invalid localStorage language value
=> Reset invalid localStorage language value

server/src/features/settings/settingsSchema.ts, shared/config/serverConfig.ts, shared/config/sharedConfig.ts
Move default DB value from shared to server config
=> Move default DB value from shared to server config

client/.eslintrc.js, client/eslint-config-client.json, client/src/app/App.tsx, client/src/views/admin/adminUtils.ts, shared/config/clientConfig.ts
Set interval to remove network error
=> Set interval to remove network error

client/src/components/LoggedInUserNavigation.tsx
Hide notification page if using direct signup
=> Hide notification page if using direct signup

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx
=> Update Solmukohta 2024 info

docker/docker-compose.yml, kubernetes/default.vars.yaml, package.json, server/src/test/globalSetup.ts
=> Update to MongoDB 7.0.6

client/src/index.tsx, client/src/markdown/KonstiInstructions.mdx, server/src/db/mongodb.ts, server/src/test/setupTests.ts, server/src/utils/initializeDatabase.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/sharedConfig.ts, shared/config/sharedConfigTypes.ts, shared/utils/signupTimes.test.ts, shared/utils/signupTimes.ts
Refactor direct signup windows config
=> Refactor direct signup windows config

client/src/test/test-components/testComponentUtils.ts, client/src/views/all-games/components/AlgorithmSignupForm.tsx, client/src/views/all-games/components/DirectSignupForm.tsx, client/src/views/all-games/components/allGamesUtils.ts, shared/config/sharedConfig.ts
Show full time on signup open when different week
Not same week:
Same week:
=> Show full time on signup open when different week

shared/utils/signupTimes.ts
Replace `toReversed` with lodash `reverse` for better browser support
=> Replace toReversed with lodash reverse

client/src/utils/timeFormatter.ts, shared/config/sharedConfig.ts
Update Solmukohta 2024 signup start time
=> Update Solmukohta 2024 signup start time

client/src/test/test-components/TestTime.tsx, client/src/utils/loadData.ts, client/src/views/logout/LogoutView.tsx
=> Use local logout if admin

client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-games/components/GameEntry.tsx
Show warning if maximum attendees missing
=> Show warning if maximum attendees missing

docker/docker-compose.yml, kubernetes/default.vars.yaml, package.json, server/src/test/globalSetup.ts
=> Update to MongoDB 7.0.7

.github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, .github/workflows/test.yml
=> Update Github Action versions

.github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml
=> Improve CI step names

client/src/views/all-games/components/SearchAndFilterCard.tsx, server/src/kompassi/getGamesFromKompassi.ts, server/src/utils/cron.test.ts, shared/config/clientConfig.ts, shared/config/past-events/solmukohta2024.ts, shared/config/serverConfig.ts, shared/config/sharedConfig.ts, shared/utils/signupTimes.ts
Archive Solmukohta 2024 config and add Ropecon 2024 config
=> Archive Solmukohta 2024 config and add Ropecon 2024 config

shared/config/serverConfig.ts
Disable program items auto update. Ropecon 2024 program is not released yet.
=> Disable program items auto update

kubernetes/production.vars.yaml
Remove Solmukohta domain konsti.solmukohta.eu
=> Remove solmukohta domain

lint-staged.config.js
Disable lint-staged lint rules
=> Disable lint-staged lint rules

.husky/pre-commit
Add back husky pre-commit hook
=> Add back husky pre-commit hook

server/src/features/player-assignment/padg/padgAssignPlayers.ts, server/src/features/player-assignment/random/randomAssignPlayers.ts, server/src/features/player-assignment/runAssignmentPadg.test.ts, server/src/features/player-assignment/runAssignmentRandom.test.ts, server/src/features/player-assignment/runAssignmentRandomPadg.test.ts, server/src/features/player-assignment/utils/getLotterySignupProgramItems.ts, server/src/features/player-assignment/utils/getLotterySignups.ts, server/src/features/player-assignment/utils/getRunRandomAndPadgInput.ts, server/src/features/player-assignment/utils/getSelectedPlayers.ts, server/src/features/statistics/statistics-helpers/programItemDataHelpers.ts, server/src/features/statistics/statistics-helpers/resultDataHelpers.ts, server/src/features/statistics/statistics-helpers/userDataHelpers.ts, server/src/types/commonTypes.ts, server/src/types/padgRandomAssignTypes.ts, server/src/types/resultTypes.ts, server/src/types/userTypes.ts
Rename `wish` to `lottery signup`
=> Rename 'wish' to 'lottery signup'

client/src/components/NotificationBar.tsx, client/src/locales/en.json, client/src/locales/fi.json, client/src/views/all-program-items/components/AlgorithmSignupForm.tsx, client/src/views/all-program-items/components/DirectSignupProgramItemForm.tsx, client/src/views/all-program-items/components/EventLog.tsx, client/src/views/all-program-items/components/LotterySignupForm.tsx, server/src/test/test-data-generation/runGenerators.ts
Add more `programType` variables to translation strings
=> Add more programType variables to translation strings

server/src/features/settings/settingsRepository.ts
Fix bug reading hidden program items from DB
=> Fix bug reading hidden program items from DB

shared/config/serverConfig.ts
Set program dataUri to Ropecon
=> Set program dataUri to Ropecon

client/src/app/AppRoutes.tsx, playwright/tests/add-favorite.spec.ts, playwright/tests/hide-program-item.spec.ts
Add e2e test for hiding program item
=> Add e2e test for hiding program item

server/src/api/apiRoutes.ts, server/src/api/sentryRoutes.ts, server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/utils/instrument.ts, server/src/utils/logger.ts, server/src/utils/sentry-winston-transport.ts, server/src/utils/server.ts
Fix `winston-transport-sentry-node` by adding a local copy of the transport
=> Fix Winston Sentry transport

server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/utils/instrument.ts, server/src/utils/logger.ts, server/src/utils/server.ts
=> Add express error handler

shared/utils/signupTimes.test.ts, shared/utils/signupTimes.ts
Fix bug with signup start time
=> Fix bug with signup start time

.eslintrc.js, client/eslint-config-client.json, server/eslint-config-server.json, shared/utils/signupTimes.test.ts
=> Add more signup time tests

client/src/views/my-program-items/components/DirectSignupRow.tsx, client/src/views/my-program-items/components/LotterySignupsByStartTimes.tsx, client/src/views/my-program-items/components/MyDirectSignupsList.tsx, client/src/views/my-program-items/components/MyLotterySignupsList.tsx, playwright/tests/add-direct-signup.spec.ts, playwright/tests/add-favorite.spec.ts, playwright/tests/add-lottery-signup.spec.ts, playwright/tests/utils.ts, server/src/test/test-data-generation/runGenerators.ts, server/src/test/test-data-generation/testDataController.ts, shared/test-types/api/populateDb.ts
Add direct signup and lottery signup e2e tests
=> Add direct signup and lottery signup e2e tests

package.json
=> Add start:test script

server/src/utils/server.ts
Improve `express` error handler based on docs: https://expressjs.com/en/guide/error-handling.html
=> Improve express error handler

shared/types/api/myProgramItems.ts, shared/types/models/user.ts
=> Combine two signup types

server/src/features/assignment/runAssignment.test.ts, server/src/features/assignment/runAssignmentPadg.test.ts, server/src/features/assignment/runAssignmentRandom.test.ts, server/src/features/assignment/runAssignmentRandomPadg.test.ts, server/src/features/assignment/runAssignmentTestUtils.ts, server/src/features/assignment/utils/removeOverlapSignups.test.ts, server/src/features/assignment/utils/saveUserSignupResults.test.ts, server/src/features/assignment/utils/updateMovedProgramItems.test.ts, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/direct-signup/directSignupRepository.test.ts, server/src/features/kompassi-login/kompassiLoginController.test.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.test.ts, server/src/features/program-item/programItemController.test.ts, server/src/features/program-item/programItemRepository.test.ts, server/src/features/serial/serialRepository.test.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsRepository.test.ts, server/src/features/user/event-log/eventLogRepository.test.ts, server/src/features/user/group/groupController.test.ts, server/src/features/user/session-restore/sessionRestoreController.test.ts, server/src/features/user/userRepository.test.ts, server/src/kompassi/test/getProgramItemsFromKompassi.test.ts, server/src/test/test-data-generation/generators/createEventLogItems.ts, server/src/test/test-data-generation/generators/createLotterySignups.ts, server/src/test/test-data-generation/generators/createSettings.ts, server/src/test/test-data-generation/generators/createSignups.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/test/utils/unsafelyUnwrapResult.ts, server/src/utils/cron.test.ts
Inline `unsafelyUnwrapResult` calls and rename to `unsafelyUnwrap`
=> Inline unsafelyUnwrapResult calls and rename to unsafelyUnwrap

.github/actionlint-matcher.json, .github/workflows/deploy-prod.yml, .github/workflows/deploy-staging.yml, .github/workflows/test.yml
Add `actionlint` to CI pipeline: https://github.com/rhysd/actionlint
=> Add actionlint to CI pipeline

client/src/locales/fi.ts, shared/config/serverConfig.ts
Enable program updates on staging
=> Enable program updates on staging

server/src/features/assignment/random/utils/runRandomAssignment.ts, server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/kompassi/hitpoint/kompassiProgramItemMapperHitpoint.ts, server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, server/src/kompassi/ropecon/kompassiProgramItemMapperRopecon.ts, server/src/kompassi/ropecon/kompassiProgramItemRopecon.ts, server/src/kompassi/solmukohta/kompassiProgramItemMapperSolmukohta.ts, server/src/kompassi/test/mockKompassiProgramItemRopecon.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, shared/tests/testProgramItem.ts, shared/types/models/programItem.ts
Kompassi program item schema improvements
=> Kompassi program item schema improvements

client/src/index.tsx, server/src/utils/instrument.ts, server/src/utils/logger.ts, shared/config/sharedConfig.ts
Increase Sentry error max length
=> Increase Sentry error max length

client/src/views/all-program-items/components/ProgramItemInfo.tsx
=> Preserve description line breaks

server/src/kompassi/ropecon/kompassiProgramItemRopecon.ts, shared/config/serverConfig.ts, shared/config/sharedConfig.ts
=> Add RPG and larp configs

server/src/features/assignment/padg/utils/assignPadg.ts, server/src/features/assignment/padg/utils/calculateHappiness.ts, server/src/features/assignment/padg/utils/runPadgAssignment.ts, server/src/features/assignment/random/utils/runRandomAssignment.ts, server/src/features/assignment/utils/formatResults.ts, server/src/types/declarations/eventassigner-js.ts, server/src/types/padgRandomAssignTypes.ts
=> Improve random assign logging

docker/docker-compose.yml, kubernetes/default.vars.yaml, package.json, server/src/test/globalSetup.ts
=> Update dev MongoDB to 7.0.11

client/src/components/PopularityInfo.tsx, client/src/theme.ts, client/src/views/all-program-items/components/ProgramItemHead.tsx
- Fiksataan lämpömittari-ikonin asettelubugi
- Pehmennetään vähän ikonin värejä.
=> Fix thermometer icon placement

shared/utils/signupTimes.ts
Limit always open signups to convention start
=> Limit always open signups to convention start

server/src/kompassi/ropecon/kompassiProgramItemMapperRopecon.ts
=> Add mapMaxAttendance

server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, shared/config/sharedConfig.ts
Add hand picked program items to Konsti. This is a temporary solutions since this data will be at Kompassi once exporter is updated.
=> Add hand picked program items to Konsti

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/components/ProgramItemEntry.tsx, client/src/views/all-program-items/components/ProgramItemErrors.tsx, client/src/views/all-program-items/components/ProgramItemHead.tsx, client/src/views/all-program-items/components/SignupsInfo.tsx
UI: Add missing min participants error and refactor errors
=> Add missing min participants error and refactor errors

server/src/kompassi/ropecon/kompassiProgramItemRopecon.ts
=> Default min attendance to one

server/package.json, yarn.lock
Update eventassigner-random to fix invalid input handling
=> Update eventassigner-random to fix invalid input handling

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/SearchAndFilterCard.tsx, client/src/views/all-program-items/components/searchAndFilterUtils.ts, shared/types/models/programItem.ts
Improve tag and language filter handling
=> Improve tag and language filter handling

server/src/test/kompassi-data-dumps/program-ropecon-2024.json
Update Ropecon 2024 program dump
=> Update Ropecon 2024 program dump

client/src/views/all-program-items/components/ProgramItemHead.tsx
Don't show 'need more participants' if no Konsti signup
=> Don't show 'need more participants' if no Konsti signup

shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/past-events/solmukohta2024.ts, shared/config/sharedConfig.ts, shared/config/sharedConfigTypes.ts, shared/utils/signupTimes.test.ts, shared/utils/signupTimes.ts
=> Fix signup windows config

server/src/features/kompassi-login/kompassiLoginService.ts, server/src/features/program-item/programItemController.test.ts, server/src/features/sentry-tunnel/sentryTunnelService.ts, server/src/kompassi/getProgramItemsFromFullProgram.ts, server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/kompassi/hitpoint/getProgramItemsFromFullProgramHitpoint.ts, server/src/kompassi/hitpoint/kompassiProgramItemHitpoint.ts, server/src/kompassi/hitpoint/kompassiProgramItemMapperHitpoint.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, server/src/kompassi/solmukohta/getProgramItemsFromFullProgramSolmukohta.ts, server/src/kompassi/test/getProgramItemsFromKompassi.test.ts, server/src/kompassi/test/mockKompassiProgramItemHitpoint.ts
Type Kompassi return value as unknown
=> Type Kompassi return value as unknown

server/package.json, server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/test/kompassi-data-dumps/program-ropecon-2024.json, server/src/test/scripts/updateKompassiDataDump.ts, shared/config/clientConfig.ts, shared/config/sharedConfig.ts
Ropecon 2024 program config updates
=> Ropecon 2024 program config updates

client/src/markdown/AboutKonsti.mdx, client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, client/src/markdown/components/CurrentTime.tsx, client/src/markdown/components/CurrentTimezone.tsx, client/src/markdown/components/En.tsx, client/src/markdown/components/Expand.tsx, client/src/markdown/components/Fi.tsx, client/src/markdown/components/FinnishTime.tsx, client/src/markdown/components/FinnishTimezone.tsx, client/src/markdown/components/Hitpoint.tsx, client/src/markdown/components/LoginKompassi.tsx, client/src/markdown/components/LoginLocal.tsx, client/src/markdown/components/Ropecon.tsx, client/src/markdown/components/SignupDirect.tsx, client/src/markdown/components/SignupLottery.tsx, client/src/markdown/components/Solmukohta.tsx
Info page review round and style improvements
=> Info page review round and style improvements

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, client/src/markdown/components/Expand.tsx
Small changes to info page styles
=> Small changes to info page styles

shared/config/serverConfig.ts
=> Enable cronjobs in prod

.eslintrc.js, client/eslint-config-client.json, client/src/views/all-program-items/components/AllProgramItemsList.tsx, client/src/views/all-program-items/components/ProgramItemInfo.tsx, server/eslint-config-server.json, server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/utils/sentry-winston-transport.ts, shared/utils/signupTimes.test.ts, yarn.config.cjs
Enable eslint rule `explicit-function-return-type`
https://typescript-eslint.io/rules/explicit-function-return-type/
=> Enable eslint rule explicit-function-return-type

client/src/components/NotificationBar.tsx, client/src/locales/en.ts, client/src/locales/fi.ts, client/src/services/userServices.ts, client/src/views/all-program-items/components/EventLog.tsx, client/src/views/all-program-items/components/EventLogNewAssignment.tsx, client/src/views/all-program-items/components/EventLogNoAssignment.tsx, server/src/api/apiRoutes.ts, server/src/features/assignment/padg/padgAssignment.ts, server/src/features/assignment/random/randomAssignment.ts, server/src/features/assignment/runAssignment.test.ts, server/src/features/assignment/runAssignment.ts, server/src/features/assignment/runAssignmentTestUtils.ts, server/src/features/assignment/utils/getGroupCreators.ts, server/src/features/assignment/utils/getGroupMembers.ts, server/src/features/assignment/utils/getLotterySignups.ts, server/src/features/assignment/utils/getRunRandomAndPadgInput.ts, server/src/features/assignment/utils/runAssignmentStrategy.ts, server/src/features/assignment/utils/saveResults.ts, server/src/features/assignment/utils/saveUserSignupResults.test.ts, server/src/features/assignment/utils/saveUserSignupResults.ts, server/src/features/user/event-log/eventLogController.ts, server/src/features/user/event-log/eventLogRepository.test.ts, server/src/features/user/event-log/eventLogRepository.ts, server/src/features/user/event-log/eventLogService.ts, server/src/test/setupTests.ts, server/src/test/test-data-generation/generators/createEventLogItems.ts, server/src/types/userTypes.ts, shared/constants/apiEndpoints.ts, shared/types/models/eventLog.ts
Add "no lottery signup" event type
=> Add "no lottery signup" event type

server/src/test/kompassi-data-dumps/program-ropecon-2024.json, shared/config/sharedConfig.ts
=> Update Konsti larps

server/src/features/assignment/utils/getAssignmentBonus.ts, server/src/features/assignment/utils/getList.test.ts, server/src/features/assignment/utils/getList.ts, server/src/features/program-item/programItemController.test.ts, shared/config/serverConfig.ts, shared/tests/testProgramItem.ts
Implement additional lottery first time bonus if user has previous failed lottery signups
=> Implement additional first signup bonus

server/src/features/assignment/padg/utils/runPadgAssignment.ts, server/src/features/assignment/random/utils/runRandomAssignment.ts, server/src/features/assignment/utils/getAssignmentBonus.ts, server/src/features/assignment/utils/getList.test.ts, server/src/features/assignment/utils/getList.ts
Don't lose first time bonus if program item is canceled
=> Don't lose first time bonus if program item is canceled

server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, shared/config/sharedConfig.ts
=> Add meetup to Konsti

server/src/features/assignment/runAssignment.test.ts
Add integration test for additional first signup bonus
=> Add integration test for additional first signup bonus

client/src/markdown/KonstiInstructions.mdx, server/src/test/kompassi-data-dumps/program-ropecon-2024.json
=> Add program organizer help

client/src/markdown/KonstiInstructions.mdx
=> Info page proofing

server/src/test/kompassi-data-dumps/program-ropecon-2024.json, shared/config/sharedConfig.ts
Add program item to revolving door
=> Add program item to revolving door

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/components/ProgramItemPage.tsx, server/src/test/kompassi-data-dumps/program-ropecon-2024.json
=> Improve not found text

server/src/features/assignment/runAssignment.test.ts
Add integration test for replacing direct signup with lottery result
=> Add integration test for replacing direct signup with lottery result

client/src/locales/fi.ts, server/src/features/assignment/runAssignment.ts, server/src/features/assignment/utils/getGroupMembers.ts, server/src/features/assignment/utils/getRunRandomAndPadgInput.ts, server/src/features/assignment/utils/saveResults.ts, server/src/features/assignment/utils/saveUserSignupResults.test.ts, server/src/features/assignment/utils/saveUserSignupResults.ts
Add no signup event to group members
=> Add no signup event to group members

client/src/views/all-program-items/components/ProgramItemInfo.tsx
Fix game system row in program item view
=> Fix game system row in program item view

client/src/views/all-program-items/components/FeedbackForm.tsx
Don't allow sending empty feedback
=> Don't allow sending empty feedback

client/src/test/test-components/TestTime.tsx, client/src/views/group/GroupView.tsx, shared/utils/initializeDayjs.ts
Show group blocking program items from same time
=> Show group blocking program items from same time

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/group/GroupView.tsx, server/src/test/kompassi-data-dumps/program-ropecon-2024.json
Show dynamic list of lottery program types on group view
=> Show dynamic list of lottery program types on group view

server/src/features/assignment/runAssignment.test.ts, server/src/features/assignment/utils/getAttendeeGroups.ts, server/src/features/assignment/utils/getGroupCreators.ts, server/src/features/assignment/utils/getGroupMembers.ts, server/src/features/assignment/utils/getLotterySignupProgramItems.ts, server/src/features/assignment/utils/getStartingProgramItems.ts, server/src/features/serial/serialRepository.ts, server/src/features/statistics/statistics-helpers/userDataHelpers.ts, server/src/test/test-data-generation/generators/createLotterySignups.ts
=> Fix flaky integration test

client/src/components/ErrorMessage.tsx, client/src/components/InfoText.tsx, client/src/locales/en.ts, client/src/locales/fi.ts, client/src/theme.ts, client/src/utils/icons.ts, client/src/views/all-program-items/components/DirectSignupForm.tsx, client/src/views/all-program-items/components/DirectSignupProgramItem.tsx, client/src/views/all-program-items/components/LotterySignupForm.tsx, client/src/views/all-program-items/components/LotterySignupProgramItem.tsx, client/src/views/all-program-items/components/ProgramItemEntry.tsx, client/src/views/all-program-items/components/ProgramItemErrors.tsx, client/src/views/all-program-items/components/ProgramItemInfo.tsx, client/src/views/all-program-items/components/RevolvingDoorProgramItemsInfo.tsx, client/src/views/all-program-items/components/SignupInfo.tsx, client/src/views/group/GroupView.tsx
- Unify styles for info, warning and error messages
- Add warning message if signing up to a lottery with a direct sign-up for the same time slot.
=> Unify info/warn/error message styles. Add missing warning

server/src/test/kompassi-data-dumps/program-ropecon-2024.json, shared/config/sharedConfig.ts
=> Adjust larp configs

client/src/views/all-program-items/components/LotterySignupForm.tsx
=> Remove extra space

client/src/views/all-program-items/components/SignupHelpText.tsx, shared/config/sharedConfig.ts
Change signup help text cut time to `isAfter`
=> Change signup help text cut time to isAfter

client/src/test/test-components/TestTime.tsx, client/src/utils/timeFormatter.ts
=> Add date to test time

client/src/views/helper/HelperView.tsx
Helper default view to password management
=> Helper default view to password management

client/src/locales/en.ts, client/src/locales/fi.ts
Fix accessibility descriptions
=> Fix accessibility descriptions

client/src/views/my-program-items/myProgramItemsSlice.ts
=> Fix loading favorites

server/src/test/kompassi-data-dumps/program-ropecon-2024.json, shared/config/sharedConfig.ts
Disable Konsti signup from larp
=> Disable Konsti signup from larp

server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, server/src/test/kompassi-data-dumps/program-ropecon-2024.json, shared/config/sharedConfig.ts
Add config to toggle invalid start time reporting
=> Add config to toggle invalid start time reporting

server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts
=> Fix error log syntax

shared/config/serverConfig.ts
=> Disable cronjobs

client/src/index.tsx, playwright/tests/directSignup.spec.ts, playwright/tests/lotterySignup.spec.ts, server/src/kompassi/hitpoint/getProgramItemsFromFullProgramHitpoint.ts, server/src/utils/instrument.ts, server/src/utils/logger.ts, shared/config/index.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/past-events/solmukohta2024.ts, shared/config/sentryConfig.ts, shared/config/sharedConfig.ts
Move sentry config to separate file
=> Move sentry config to separate file

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/utils/getAttendeeType.ts, server/src/kompassi/getProgramItemsFromFullProgram.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/test/getProgramItemsFromKompassi.test.ts, server/src/kompassi/test/mockKompassiProgramItemTracon.ts, server/src/kompassi/tracon/getProgramItemsFromFullProgramTracon.ts, server/src/kompassi/tracon/kompassiProgramItemMapperTracon.ts, server/src/kompassi/tracon/kompassiProgramItemTracon.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/ropecon2024.ts, shared/types/models/programItem.ts
=> Add Tracon 2024 configs

shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/index.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/past-events/ropecon2024.ts, shared/config/past-events/solmukohta2024.ts
Refactor how old event configs are stored
=> Refactor how old event configs are stored

server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/test/mockKompassiProgramItem.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, shared/config/eventConfig.ts, shared/config/serverConfig.ts
Read in multiple schedule items
=> Read in multiple schedule items

client/src/test/test-components/testComponentUtils.ts, client/src/views/all-program-items/components/SignupsInfo.tsx, server/src/features/program-item/programItemController.test.ts, server/src/features/program-item/programItemController.ts, server/src/features/program-item/programItemService.ts, server/src/features/program-item/programItemUtils.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/test/mockKompassiProgramItem.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, server/src/utils/authHeader.ts, server/src/utils/jwt.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/serverConfig.ts
Allow hiding participant list for some program types
=> Allow hiding participant list for some program types

shared/config/serverConfig.ts
Enable program update on staging
=> Enable program update on staging

client/src/components/Dropdown.tsx, client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/allProgramItemsSlice.ts
=> Fix Tracon 2024 tags

client/src/markdown/AboutKonsti.mdx, client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, client/src/markdown/components/Hide.tsx, client/src/markdown/components/Tracon.tsx, shared/config/clientConfig.ts
=> Update Tracon 2024 info page

server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/test/mockKompassiProgramItem.ts, server/src/test/kompassi-data-dumps/program-tracon-2024.json, server/src/test/test-data-generation/generators/createProgramItems.ts, server/src/utils/cron.test.ts, shared/config/serverConfig.ts
=> Add slug to scheduleItem

client/src/views/admin/adminSlice.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, server/src/test/kompassi-data-dumps/program-tracon-2024.json
For example `https://dev.ropekonsti.fi/program/list?programType=fleamarket`
=> Get program type from query parameter

client/src/test/test-settings/testSettingsSlice.ts, client/src/views/admin/adminSlice.ts, client/src/views/all-program-items/allProgramItemsSlice.ts, client/src/views/group/groupSlice.ts, client/src/views/login/loginSlice.ts, client/src/views/my-program-items/myProgramItemsSlice.ts
=> Type reducer return values

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/admin/components/SignupStrategySelector.tsx, server/src/features/assignment/assignmentController.ts, server/src/features/assignment/padg/padgAssignment.ts, server/src/features/assignment/padg/utils/runPadgAssignment.ts, server/src/features/assignment/random/randomAssignment.ts, server/src/features/assignment/random/utils/runRandomAssignment.ts, server/src/features/assignment/runAssignment.test.ts, server/src/features/assignment/runAssignment.ts, server/src/features/assignment/runAssignmentPadg.test.ts, server/src/features/assignment/runAssignmentRandom.test.ts, server/src/features/assignment/runAssignmentRandomPadg.test.ts, server/src/features/assignment/utils/runAssignmentAlgorithm.ts, server/src/features/assignment/utils/runAssignmentStrategy.ts, server/src/features/assignment/utils/saveResults.ts, server/src/features/results/resultsRepository.test.ts, server/src/features/results/resultsRepository.ts, server/src/test/scripts/testAssignment.ts, server/src/types/resultTypes.ts, server/src/utils/cron.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/past-events/ropecon2024.ts, shared/config/past-events/solmukohta2024.ts
Rename `assignmentStrategy` to `assignmentAlgorithm`
=> Rename assignmentStrategy to assignmentAlgorithm

client/src/views/all-program-items/components/SignupHelpText.tsx, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/utils/signupTimes.test.ts, shared/utils/signupTimes.ts
Add `fixedLotterySignupTime` config
=> Add fixedLotterySignupTime config

client/src/components/LoggedInUserNavigation.tsx, client/src/markdown/components/SignupDirect.tsx, client/src/markdown/components/SignupLottery.tsx, client/src/types/reduxTypes.ts, client/src/views/admin/adminSlice.ts, client/src/views/admin/adminThunks.ts, client/src/views/admin/components/SignupStrategySelector.tsx, client/src/views/all-program-items/components/AllProgramItemsList.tsx, client/src/views/all-program-items/components/LotterySignupProgramItem.tsx, client/src/views/all-program-items/components/ProgramItemEntry.tsx, client/src/views/all-program-items/components/ProgramItemHead.tsx, client/src/views/all-program-items/components/ProgramItemPage.tsx, client/src/views/all-program-items/components/SignupHelpText.tsx, client/src/views/all-program-items/components/SignupInfo.tsx, client/src/views/my-program-items/MyProgramItemsView.tsx, playwright/tests/lotterySignup.spec.ts, server/src/features/program-item/programItemUtils.ts, server/src/features/settings/settingsController.test.ts, shared/config/eventConfigTypes.ts, shared/config/serverConfig.ts, shared/types/api/settings.ts, shared/types/models/programItem.ts, shared/types/models/settings.ts
Separate event and program item signup strategy
=> Separate event and program item signup strategy

client/src/views/all-program-items/components/LotterySignupProgramItem.tsx, client/src/views/all-program-items/components/ProgramItemEntry.tsx, client/src/views/all-program-items/components/ProgramItemHead.tsx, client/src/views/all-program-items/components/SignupInfo.tsx, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2023.ts, shared/config/past-events/ropecon2024.ts, shared/config/past-events/solmukohta2024.ts
Remove `manualSignupMode` config
=> Remove manualSignupMode config

shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/ropecon2024.ts, shared/utils/signupTimes.test.ts, shared/utils/signupTimes.ts
Add config `enableRollingSignupPreviousDay`
=> Add config enableRollingSignupPreviousDay

client/src/app/App.tsx, client/src/views/admission-ticket/AdmissionTicketView.tsx, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/ProgramItemPage.tsx, client/src/views/group/GroupView.tsx, client/src/views/helper/HelperView.tsx, client/src/views/my-program-items/MyProgramItemsView.tsx, eslint.config.mjs, package.json, yarn.lock
Install `eslint-plugin-react-hooks-addons` to notify about unused `useEffect` deps.
Required deps can be marked with `/* effect dep */`
=> Install eslint-plugin-react-hooks-addons

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/components/DirectSignupForm.tsx, client/src/views/all-program-items/components/allProgramItemsUtils.ts, server/src/test/kompassi-data-dumps/program-tracon-2024.json, server/src/test/scripts/updateKompassiDataDump.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts
Add entry condition config to add required checkboxes
=> Add entry condition config to add required checkboxes

client/src/test/test-components/TestTime.tsx, client/src/test/test-settings/testSettingsThunks.ts, client/src/utils/loadData.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/DirectSignupForm.tsx, client/src/views/all-program-items/components/DirectSignupProgramItem.tsx, client/src/views/helper/HelperView.tsx, client/src/views/login/loginThunks.ts, client/src/views/my-program-items/MyProgramItemsView.tsx, client/src/views/my-program-items/components/DirectSignupRow.tsx
Don't load program items twice on page load
=> Don't load program items twice on page load

client/src/views/all-program-items/components/ProgramItemEntry.tsx, client/src/views/all-program-items/components/ProgramItemHead.tsx, client/src/views/all-program-items/components/SignupHelpText.tsx, client/src/views/all-program-items/components/SignupInfo.tsx, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/kompassi/test/mockKompassiProgramItem.ts, server/src/test/kompassi-data-dumps/program-tracon-2024.json, server/src/test/test-data-generation/generators/createProgramItems.ts
Read in `konsti:isPlaceholder` from Kompassi
=> Read in konsti:isPlaceholder from Kompassi

client/src/services/myProgramItemsServices.test.ts, client/src/utils/getUpcomingProgramItems.ts, client/src/views/my-program-items/components/DirectSignupRow.tsx, client/src/views/program-item/signup/ProgramItemSignup.tsx, client/src/views/program-item/signup/components/DirectSignupForm.tsx, client/src/views/program-item/signup/components/DirectSignupProgramItem.tsx, client/src/views/program-item/signup/components/SignupHelpText.tsx, server/src/features/assignment/utils/saveUserSignupResults.ts, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/direct-signup/directSignupRepository.test.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/direct-signup/directSignupService.ts, server/src/features/direct-signup/directSignupTypes.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/features/user/userUtils.ts, server/src/test/mock-data/mockUser.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/types/api/myProgramItems.ts, shared/utils/signupTimes.ts
* Show fleamarket signups till slot end time
* Don't send program item `startTime` from client, read it from program item on backend
=> Show fleamarket signups till slot end time

server/package.json, server/src/features/assignment/padg/padgAssignment.ts, server/src/features/assignment/random/randomAssignment.ts, server/src/features/assignment/utils/getRandomAndPadgInput.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.ts, server/src/features/program-item-popularity/utils/updateWithAssign.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/test/kompassi-data-dumps/program-tracon-2024.json, server/src/test/test-data-generation/generateTestData.ts, server/src/test/test-data-generation/generateTestDataCli.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts
=> Improve dummy data generation

server/src/kompassi/kompassiProgramItemMapper.ts
Read larp max attendees properly
=> Read larp max attendees properly

shared/config/serverConfig.ts
Disable staging and prod cronjobs
=> Disable staging and prod cronjobs

server/src/features/statistics/similarUsernames.ts
Improve similar usernames logic
=> Improve similar usernames logic

shared/config/eventConfig.ts, shared/config/past-events/tracon2024.ts
=> Add Hitpoint 2024 config

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx
=> Update Hitpoint info page

server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/test/kompassi-data-dumps/program-tracon hitpoint-2024.json, shared/config/clientConfig.ts, shared/config/eventConfig.ts, shared/config/serverConfig.ts
=> Read in Tracon 2024 data

client/src/locales/fi.ts, client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, server/src/kompassi/kompassiProgramItemMapper.ts, shared/config/clientConfig.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/tracon2024.ts
=> Hitpoint 2024: add workshops

server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, server/src/test/kompassi-data-dumps/program-tracon hitpoint-2024.json, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/hitpoint2023.ts, shared/config/past-events/ropecon2024.ts, shared/config/past-events/solmukohta2024.ts, shared/config/past-events/tracon2024.ts
Update Hitpoint 2024 custom details
=> Update Hitpoint 2024 custom details

docker/docker-compose.yml, kubernetes/default.vars.yaml, package.json
=> Update test mongodb to 7.0.15

shared/config/eventConfig.ts
Update Tracon Hitpont 2024 languages
=> Update Tracon Hitpont 2024 languages

client/src/views/program-item/signup/components/SignupHelpText.tsx
Fix regression in signup status
=> Fix regression in signup status

.github/workflows/test.yml
=> Update actionlint 1.7.5

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/SearchAndFilterCard.tsx
Add the possibility to only show program items to which you can sign up to right now.
=> Add filter for hiding full program items in program list.

.github/workflows/test.yml, client/src/views/login/LoginView.tsx, client/src/views/login/components/LoginForm.tsx, playwright/tests/login.spec.ts
=> Fix root redirect after login

client/src/app/AppRoutes.tsx
=> Add back required export

client/assets/robots.txt, client/package.json, client/webpack.config.ts, yarn.lock
Add robots.txt and block crawler causing errors
=> Add robots.txt and block crawler causing errors

.yarnrc.yml, client/package.json, client/webpack.config.ts, server/package.json, server/src/utils/server.ts, yarn.lock
Update express v5: https://expressjs.com/en/guide/migrating-5.html
=> Update express v5

client/src/utils/getUpcomingProgramItems.ts, client/src/views/my-program-items/components/DirectSignupItem.tsx, client/src/views/my-program-items/components/DirectSignupsByStartTimes.tsx, client/src/views/my-program-items/components/LotterySignupsByStartTimes.tsx, client/src/views/my-program-items/components/MyDirectSignupsList.tsx, client/src/views/my-program-items/components/MyLotterySignupsList.tsx, client/src/views/my-program-items/myProgramItemsSlice.ts, client/src/views/my-program-items/utils/getMissedSignups.ts, client/src/views/program-item/ProgramItemEntry.tsx, client/src/views/program-item/programItemUtils.ts, client/src/views/program-item/signup/ProgramItemSignup.tsx, client/src/views/program-item/signup/components/LotterySignupForm.tsx, client/src/views/program-item/signup/components/LotterySignupProgramItem.tsx, server/src/features/assignment/utils/formatResults.ts, server/src/features/assignment/utils/getList.test.ts, server/src/features/assignment/utils/getList.ts, server/src/features/results/resultsRepository.ts, server/src/features/statistics/statistics-helpers/programItemDataHelpers.ts, server/src/features/user/lottery-signup/lotterySignupRepository.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, server/src/test/test-data-generation/generators/createLotterySignups.ts, server/src/types/resultTypes.ts, shared/types/api/myProgramItems.ts, shared/types/models/groups.ts, shared/types/models/result.ts, shared/types/models/user.ts
Split direct and lottery signup types to make refactoring easier
=> Split direct and lottery signup types

playwright/tests/directSignup.spec.ts, shared/config/eventConfig.ts, shared/config/past-events/hitpoint2024.ts
=> Add Ropecon 2025 config

shared/config/eventConfigTypes.ts
Add local+kompassi login provider
=> Add local+kompassi login provider

client/src/components/ScrollToTopButton.tsx
Fine-tune styling for scroll to top button.
=> Fine-tune scroll to top button styling.

client/src/components/Accordion.tsx, client/src/components/Checkbox.tsx, client/src/components/PrivacyPolicy.tsx, client/src/views/login/components/KompassiLoginUsernameForm.tsx, client/src/views/registration/components/RegistrationForm.tsx, playwright/tests/kompassiLogin.spec.ts
When Kompassi login is in use, the users now have to accept privacy policy before using Konsti.
=> Show privacy policy for users logging in with Kompassi, too

eslint.config.ts, server/src/features/assignment/utils/removeInvalidProgramItemsFromUsers.ts, server/src/features/assignment/utils/removeOverlapLotterySignups.ts, server/src/features/assignment/utils/saveResults.ts, server/src/features/assignment/utils/saveUserSignupResults.ts, server/src/features/assignment/utils/updateMovedProgramItems.ts, server/src/features/assignment/utils/verifyUserSignups.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/feedback/feedbackRepository.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.ts, server/src/features/program-item/programItemRepository.ts, server/src/features/results/resultsRepository.ts, server/src/features/serial/serialRepository.ts, server/src/features/settings/settingsRepository.ts, server/src/features/settings/utils/removeHiddenProgramItemsFromUsers.ts, server/src/features/user/event-log/eventLogRepository.ts, server/src/features/user/group/groupService.ts, server/src/features/user/lottery-signup/lotterySignupRepository.ts, server/src/features/user/userRepository.ts, server/src/test/test-settings/testSettingsRepository.ts, server/src/utils/cron.ts, shared/utils/result.ts
Success result: don't require unnecessary undefined for empty result
Before:
```ts
return makeSuccessResult(undefined);
```
After:
```ts
return makeSuccessResult();
```
=> Success result: don't require unnecessary undefined for empty result

client/src/services/hiddenServices.ts, client/src/types/reduxTypes.ts, client/src/utils/store.ts, client/src/views/admin/AdminView.tsx, client/src/views/admin/adminSlice.ts, client/src/views/admin/adminThunks.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/RevolvingDoorProgramItemsInfo.tsx, client/src/views/program-item/body/components/AdminActionCard.tsx, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/settings/settingsController.test.ts, server/src/features/settings/settingsController.ts, server/src/features/settings/settingsRepository.test.ts, server/src/features/settings/settingsRepository.ts, server/src/features/settings/settingsSchema.ts, server/src/features/settings/settingsService.ts, server/src/features/settings/utils/removeHiddenProgramItemsFromUsers.ts, server/src/features/statistics/fixer-helpers/programItemIdFix.ts, server/src/test/setupTests.ts, shared/types/api/settings.ts, shared/types/models/settings.ts, shared/types/models/user.ts
Normalize hidden program items
=> Normalize hidden program items

client/src/services/myProgramItemsServices.ts, client/src/views/my-program-items/myProgramItemsSlice.ts, client/src/views/my-program-items/myProgramItemsThunks.ts, client/src/views/program-item/signup/components/LotterySignupForm.tsx, client/src/views/program-item/signup/components/LotterySignupProgramItem.tsx, server/src/api/apiRoutes.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/direct-signup/directSignupService.ts, server/src/features/direct-signup/directSignupTypes.ts, server/src/features/user/lottery-signup/lotterySignupController.ts, server/src/features/user/lottery-signup/lotterySignupRepository.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/utils/initializeDatabase.ts, shared/types/api/myProgramItems.ts, shared/types/models/user.ts
Send only new/removed lottery signup, not all
=>  Send only new/removed lottery signup, not all

client/src/app/AppRoutes.tsx, client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/event-log/NotificationBar.tsx, shared/config/clientConfig.ts
=> Add about page in progress notification

client/src/views/my-program-items/components/DirectSignupItem.tsx, client/src/views/program-item/signup/components/DirectSignupProgramItem.tsx, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/direct-signup/directSignupController.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/direct-signup/directSignupService.ts, shared/types/api/myProgramItems.ts
Don't pass username on signup delete
=> Don't pass username on signup delete

server/src/features/assignment/padg/utils/runPadgAssignment.ts, server/src/features/assignment/random/utils/runRandomAssignment.ts, server/src/features/assignment/utils/formatResults.ts, server/src/features/assignment/utils/getGroups.ts, server/src/features/assignment/utils/getList.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.ts
Don't return `Result` for sync function
=> Don't return Result for sync function

.github/workflows/test.yml
Update Github Actions runner to latest ubuntu
=> Update Github Actions runner to latest ubuntu

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/services/myProgramItemsServices.ts, client/src/views/my-program-items/myProgramItemsThunks.ts, client/src/views/program-item/signup/components/LotterySignupForm.tsx, playwright/tests/lotterySignup.spec.ts, server/src/features/assignment/run-assignment/runAssignment.test.ts, server/src/features/assignment/utils/formatResults.ts, server/src/features/assignment/utils/getList.test.ts, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/kompassi-login/kompassiLoginController.test.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.test.ts, server/src/features/user/group/groupController.test.ts, server/src/features/user/lottery-signup/lotterySignupController.test.ts, server/src/features/user/lottery-signup/lotterySignupController.ts, server/src/features/user/lottery-signup/lotterySignupRepository.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/features/user/session-restore/sessionRestoreController.test.ts, server/src/features/user/signup-message/signupMessageController.test.ts, server/src/features/user/userControllerPasswordReset.test.ts, server/src/features/user/userSchema.ts, server/src/features/user/userService.ts, server/src/test/mock-data/mockUser.ts, server/src/test/test-data-generation/generators/createLotterySignups.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, server/src/utils/authHeader.ts, shared/types/api/myProgramItems.ts, shared/types/api/users.ts, shared/types/models/user.ts
Add lottery signup logic and tests, add missing direct signup test
=> Add lottery signup logic and tests, add missing direct signup test

client/src/services/userServices.ts, client/src/utils/timeFormatter.ts, client/src/views/event-log/EventLog.tsx, client/src/views/event-log/NotificationBar.tsx, client/src/views/helper/components/ChangePasswordForm.tsx, client/src/views/helper/components/PasswordManagement.tsx, client/src/views/profile/ProfileView.tsx, client/src/views/program-item/signup/components/DirectSignupForm.tsx, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/direct-signup/directSignupController.ts, server/src/features/direct-signup/directSignupService.ts, server/src/features/user/event-log/eventLogController.ts, server/src/features/user/event-log/eventLogRepository.ts, server/src/features/user/event-log/eventLogService.ts, server/src/features/user/userController.ts, server/src/features/user/userControllerPasswordReset.test.ts, shared/types/api/eventLog.ts, shared/types/api/myProgramItems.ts, shared/types/api/users.ts
Don't pass username if it should be read from JWT
=> Don't pass username if it should be read from JWT

package.json, server/package.json, server/src/test/scripts/loadPastEventDataToDb.ts
Add script to load past event data
=> Add script to load past event data

playwright/tests/login.spec.ts
=> Fix flaky e2e test

server/src/api/apiRoutes.ts, server/src/features/assignment/assignmentController.test.ts, server/src/features/sentry-tunnel/sentryTunnelController.test.ts, server/src/features/sentry-tunnel/sentryTunnelController.ts, server/src/features/user/event-log/eventLogController.test.ts, server/src/features/user/event-log/eventLogRepository.ts, shared/types/api/errors.ts, shared/types/api/eventLog.ts
Add API tests for assignment, sentry tunnel and event log
=> Add API tests for assignment, sentry tunnel and event log

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/my-program-items/components/LotterySignupsByStartTimes.tsx, client/src/views/program-item/head/ProgramItemHead.tsx, client/src/views/program-item/head/components/ProgramItemHeadSignupInfo.tsx, client/src/views/program-item/signup/components/LotterySignupForm.tsx, client/src/views/program-item/signup/components/LotterySignupProgramItem.tsx
Inline 'more attendees' text with attendee count
Before:
After:
=> Inline 'more attendees' text with attendee count

client/src/index.tsx, client/src/state/loading/loadingSlice.ts, client/src/utils/store.ts, client/src/views/all-program-items/components/AllProgramItemsList.tsx, client/src/views/program-item/ProgramItemEntry.tsx, client/src/views/program-item/ProgramItemView.tsx, client/src/views/program-item/signup/ProgramItemSignup.tsx, client/src/views/program-item/signup/components/DirectSignupForm.tsx, client/src/views/program-item/signup/components/DirectSignupProgramItem.tsx, client/src/views/program-item/signup/components/LotterySignupForm.tsx, client/src/views/program-item/signup/components/LotterySignupProgramItem.tsx
=> Add loading state to redux

client/src/types/reduxTypes.ts, client/src/views/admin/adminThunks.ts, client/src/views/all-program-items/allProgramItemsSlice.ts, client/src/views/all-program-items/allProgramItemsThunks.ts, client/src/views/group/groupThunks.ts, client/src/views/login/loginThunks.ts, client/src/views/my-program-items/myProgramItemsThunks.ts
Don't update Redux state if same data
=> Don't update Redux state if same data

client/src/test/test-settings/testSettingsThunks.ts, client/src/utils/loadData.ts, client/src/views/all-program-items/allProgramItemsThunks.ts
Allow program items force update
=> Allow program items force update

client/src/theme.ts
Fine-tune colors for popularity icons.
=> Tune popularity icon colors.

server/src/features/program-item-popularity/getPopularity.test.ts, server/src/features/program-item-popularity/getPopularity.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.test.ts, server/src/features/program-item-popularity/updateProgramItemPopularity.ts
Add tests for popularity levels
=> Add tests for popularity levels

client/src/views/my-program-items/myProgramItemsThunks.ts, client/src/views/program-item/head/components/ProgramItemHeadSignupInfo.tsx, client/src/views/program-item/signup/components/direct-signup/ProgramItemDirectSignup.tsx, playwright/playwrightUtils.ts, playwright/tests/about.spec.ts, playwright/tests/directSignup.spec.ts, server/src/features/direct-signup/directSignupRepository.test.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/direct-signup/directSignupService.ts, shared/types/api/myProgramItems.ts
Return participant list if program item full
=> Return participant list if program item full

server/src/features/user/group/groupService.ts
Check upcoming signups with program item start time not signup time
=> Check upcoming signups with program item start time not signup time

server/src/test/kompassi-data-dumps/program-ropecon-2025.json
Add Ropecon 2025 Kompassi data dump with redacted hosts
=> Add Ropecon 2025 Kompassi data dump with redacted hosts

server/src/test/kompassi-data-dumps/program-ropecon-2025.json
=> Update Ropecon 2025 datadump

server/src/kompassi/kompassiProgramItemMapper.ts, shared/config/eventConfig.ts
=> Add direct signup windows

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/utils/isRevolvingDoorWorkshop.ts, client/src/views/program-item/ProgramItemEntry.tsx, client/src/views/program-item/signup/components/SignupHelpText.tsx, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/kompassiProgramItemMapper.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/hitpoint2024.ts, shared/types/models/programItem.ts
Show different registration types
=> Show different registration types

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/event-log/EventLog.tsx, client/src/views/event-log/EventLogEventMessage.tsx, client/src/views/event-log/EventLogProgramItemCanceled.tsx, client/src/views/event-log/NotificationBar.tsx, client/src/views/event-log/NotificationBarEventMessage.tsx, client/src/views/my-program-items/myProgramItemsThunks.ts, playwright/tests/cancelProgramItem.spec.ts, server/src/features/assignment/run-assignment/runAssignment.ts, server/src/features/assignment/utils/removeInvalidProgramItemsFromUsers.test.ts, server/src/features/assignment/utils/removeInvalidProgramItemsFromUsers.ts, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/direct-signup/directSignupRepository.test.ts, server/src/features/direct-signup/directSignupRepository.ts, server/src/features/direct-signup/directSignupService.ts, server/src/features/program-item/programItemRepository.test.ts, server/src/features/program-item/programItemRepository.ts, server/src/features/program-item/programItemUtils.ts, server/src/features/user/lottery-signup/lotterySignupController.test.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/test/scripts/removeInvalidProgramItems.ts, server/src/test/test-data-generation/generators/createProgramItems.ts, shared/types/api/myProgramItems.ts, shared/types/models/eventLog.ts
* When program item is cancelled, remove signups and favorites
* Add event message to affected users.
=> Add program item state and mark cancelled program items

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/event-log/EventLogEventMessage.tsx, client/src/views/event-log/EventLogProgramItemMoved.tsx, client/src/views/event-log/NotificationBarEventMessage.tsx, playwright/tests/cancelProgramItem.spec.ts, playwright/tests/moveProgramItem.spec.ts, server/src/features/assignment/utils/updateMovedProgramItems.ts, server/src/features/program-item/programItemController.test.ts, server/src/features/program-item/programItemRepository.test.ts, server/src/features/user/group/groupService.ts, server/src/features/user/lottery-signup/lotterySignupRepository.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, shared/types/models/eventLog.ts
- Moved programs: remove lottery signups instead of re-writing remaining
- Add notification if user has signups and program item is moved
=> Notify about moved program items

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/event-log/EventLogProgramItemCanceled.tsx, playwright/tests/cancelProgramItem.spec.ts
Make canceled program item name a link
=> Make canceled program item name a link

client/src/views/program-item/signup/components/lottery-signup/LotterySignupForm.tsx
Show entry condition checkbox for lottery signup
=> Show entry condition checkbox for lottery signup

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/markdown/KonstiFaq.mdx, client/src/markdown/components/ProgramGuide.tsx, client/src/views/all-program-items/components/AllProgramItemsList.tsx, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts
- Add program guide to FAQ
- ![image](https://github.com/user-attachments/assets/56ba2d51-79f1-4668-ad0a-3d5b5c62ff6b)
- If Konsti search doesn't return any program items, recommend to check program guide
- ![image](https://github.com/user-attachments/assets/c459f69f-9a33-4090-9664-fd0e65c2ac67)
=> Add program guide links to Konsti

client/package.json, client/src/markdown/components/TextWithLinks.tsx, client/src/views/program-item/body/components/ProgramItemDetails.tsx, yarn.lock
=> Highlight description links

client/src/locales/en.ts, client/src/locales/fi.ts, server/src/features/statistics/datafiles/ropecon/2021/program-items.json, server/src/features/statistics/datafiles/ropecon/2022/program-items.json, server/src/features/statistics/datafiles/ropecon/2023/program-items.json, server/src/features/statistics/datafiles/ropecon/2024/program-items.json, server/src/features/statistics/datafiles/tracon-hitpoint/2023/program-items.json, server/src/features/statistics/datafiles/tracon-hitpoint/2024/program-items.json, shared/types/models/programItem.ts
Fix populate:event script by migrating old program items to current scheme
=> Fix populate:event script by migrating old program items to current scheme

client/src/views/all-program-items/AllProgramItemsView.tsx
Remove search leading debounce
=> Remove search leading debounce

client/src/utils/sessionStorage.ts, client/src/views/all-program-items/AllProgramItemsView.tsx, client/src/views/all-program-items/components/SearchAndFilterCard.tsx
Persist hide full to sessionStorage
=> Persist hide full to sessionStorage

client/src/views/program-item/body/ProgramItemBody.tsx
Highlight short description links
=> Highlight short description links

server/src/features/program-item/programItemController.test.ts, server/src/kompassi/getProgramItemsFromKompassi.ts, server/src/kompassi/kompassiProgramItem.ts, server/src/kompassi/ropecon/getProgramItemsFromFullProgramRopecon.ts, server/src/kompassi/tracon/getProgramItemsFromFullProgramTracon.ts, server/src/test/kompassi-data-dumps/program-ropecon-2025.json, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts, shared/config/past-events/hitpoint2024.ts, shared/config/past-events/ropecon2024.ts, shared/config/past-events/tracon2024.ts, shared/config/serverConfig.ts
Do not log missing schedule items if cancelled
=> Don't log missing scheduleItems if program item cancelled

server/src/test/kompassi-data-dumps/program-ropecon-2025.json, shared/config/eventConfig.ts
Add speed painting contest signup question
=> Add speed painting contest signup question

client/src/locales/fi.ts, client/src/markdown/KonstiFaq.mdx
Remove duplicate FAQ entry, fix group advice text
=> Remove duplicate FAQ entry, fix group advice text

client/src/locales/en.ts, client/src/locales/fi.ts, client/src/views/helper/components/PasswordManagement.tsx, server/src/features/user/userService.ts, shared/types/api/users.ts
=> Don't allow changing password for Kompassi login user

.github/workflows/test.yml, docker/docker-compose.yml, kubernetes/default.vars.yaml, server/src/test/globalSetup.ts, server/src/test/scripts/dockerDb.ts
Update mongoDB 8.0.10 -> 8.0.11
=> Update mongoDB 8.0.10 -> 8.0.11

server/src/features/direct-signup/directSignupRepository.ts, server/src/features/program-item/programItemRepository.test.ts, server/src/features/program-item/programItemRepository.ts, server/src/features/program-item/programItemUtils.ts, server/src/test/kompassi-data-dumps/program-ropecon-2025.json, shared/config/eventConfig.ts
Don't remove signup collection when program item is cancelled, not removed
=> Don't remove signup collection when program item is cancelled, not removed

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, playwright/tests/group.spec.ts, playwright/tests/login.spec.ts, playwright/tests/lotterySignup.spec.ts, server/src/features/direct-signup/directSignupController.test.ts, server/src/features/statistics/datafiles/solmukohta/2024/program-items.json, server/src/features/statistics/datafiles/tracon/2024/program-items.json, server/src/features/user/lottery-signup/lotterySignupController.test.ts, server/src/features/user/lottery-signup/lotterySignupService.ts, server/src/test/scripts/loadPastEventDataToDb.ts, shared/config/clientConfig.ts, shared/config/eventConfig.ts, shared/config/past-events/ropecon2025.ts, shared/config/serverConfig.ts, shared/utils/signupTimes.ts
=> Add Tracon 2025 config

server/src/features/statistics/statGenerator.ts, server/src/features/statistics/statistics-helpers/getProgramItemStats.ts, server/src/features/statistics/statistics-helpers/getResultsStats.ts, server/src/features/statistics/statistics-helpers/getUserStats.ts, server/src/features/statistics/statistics-helpers/programItemDataHelpers.ts, server/src/types/commonTypes.ts
Improve program item popularity statistics function
=> Improve program item popularity statistics function

client/src/markdown/KonstiFaq.mdx, client/src/markdown/KonstiInstructions.mdx, shared/config/clientConfig.ts
Update info page for Tracon 2025
=> Update info page for Tracon 2025

client/src/views/all-program-items/components/SearchAndFilterCard.tsx, client/src/views/program-item/body/ProgramItemBody.tsx, shared/config/clientConfig.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts
=> Search fields for Tracon 2025

client/src/test/test-components/testComponentUtils.ts, client/src/views/program-item/head/ProgramItemHead.tsx, shared/utils/signupTimes.ts
Show number of signups after lottery, not when direct signup starts
=> Show number of signups after lottery

playwright/tests/kompassiLogin.spec.ts, server/src/features/user/userRepository.ts, server/src/test/test-data-generation/generators/createUsers.ts, server/src/types/userTypes.ts
Pass `emailNotificationPermitAsked` for new user, don't determine it based on email value
=> Fix emailNotificationPermitAsked new user value

playwright/tests/kompassiLogin.spec.ts, server/.env.sample, server/src/features/user/group/groupController.test.ts, server/src/features/user/group/groupService.ts
Add parent logic to join group
=> Add parent logic to join group

client/src/views/program-item/ProgramItemEntry.tsx, client/src/views/program-item/head/ProgramItemHead.tsx, server/src/test/kompassi-data-dumps/program-tracon-2025.json, shared/config/clientConfig.ts
Hide language tag if only one language
=> Hide language tag if only one language

server/src/features/assignment/run-assignment/runAssignment.ts, server/src/features/assignment/utils/getUpcomingLotterySignups.ts, server/src/features/assignment/utils/removeOverlapLotterySignups.test.ts, server/src/features/assignment/utils/removeOverlapLotterySignups.ts, server/src/features/user/group/groupService.ts, shared/config/eventConfig.ts, shared/config/eventConfigTypes.ts
Feature: remove all upcoming lottery signups after lottery
=> Feature: remove all upcoming lottery signups after lottery

shared/config/eventConfig.ts
Add Tracon 2025 entry conditions
=> Add Tracon 2025 entry conditions

shared/config/eventConfig.ts
With 1900 users in lottery:
- PADG 40 seconds
- Random 5 seconds
=> Use random algorithm for Tracon 2025

server/src/features/admin/emailTestController.ts
=> Add html body to test controller email sending

server/src/features/program-item/programItemUtils.ts
Fix program item startTime bug
=> Fix program item startTime bug

server/src/features/direct-signup/directSignupRepository.ts
=> Fix lint errors
